using System.Globalization;

namespace ReVitae.Core.Localization;

public sealed class AppLocalizer
{
    public const string FallbackLanguageCode = "en";

    public static readonly IReadOnlyList<SupportedLanguage> SupportedLanguages =
    [
        new("en", "English", "English", "🇬🇧"),
        new("es", "Spanish", "Español", "🇪🇸"),
        new("fr", "French", "Français", "🇫🇷"),
        new("de", "German", "Deutsch", "🇩🇪"),
        new("pt", "Portuguese", "Português", "🇵🇹"),
        new("it", "Italian", "Italiano", "🇮🇹"),
        new("nl", "Dutch", "Nederlands", "🇳🇱"),
        new("pl", "Polish", "Polski", "🇵🇱"),
        new("uk", "Ukrainian", "Українська", "🇺🇦"),
        new("zh-Hans", "Chinese Simplified", "简体中文", "🇨🇳"),
        new("sk", "Slovak", "Slovenčina", "🇸🇰"),
        new("cs", "Czech", "Čeština", "🇨🇿")
    ];

    private static readonly IReadOnlyDictionary<string, string> EnglishTranslations = new Dictionary<string, string>
    {
        [TranslationKeys.HeaderSubtitle] = "Create a simple CV preview and export a plain PDF.",
        [TranslationKeys.OpenSetup] = "Open setup",
        [TranslationKeys.OpenAbout] = "About",
        [TranslationKeys.OpenUploadCv] = "Upload another CV",
        [TranslationKeys.OpenCreateNewCv] = "Create new CV",
        [TranslationKeys.OpenTemplates] = "Open templates",
        [TranslationKeys.Confirm] = "OK",
        [TranslationKeys.Cancel] = "Cancel",
        [TranslationKeys.OpenExpandPreview] = "Expand preview",
        [TranslationKeys.MainPersonalInformation] = "Main / Personal information",
        [TranslationKeys.PersonalInformationValidationErrors] = "{0} errors",
        [TranslationKeys.FirstName] = "First name",
        [TranslationKeys.LastName] = "Last name",
        [TranslationKeys.ProfessionalTitle] = "Professional title",
        [TranslationKeys.Email] = "Email",
        [TranslationKeys.Phone] = "Phone",
        [TranslationKeys.Location] = "Location",
        [TranslationKeys.LinkedInUrl] = "LinkedIn URL",
        [TranslationKeys.PortfolioUrl] = "Portfolio / website URL",
        [TranslationKeys.GitHubUrl] = "GitHub URL",
        [TranslationKeys.ShortSummary] = "Short summary",
        [TranslationKeys.ShortSummaryPlaceholder] = "Write two to four sentences about your professional profile.",
        [TranslationKeys.ProfilePhoto] = "Profile photo",
        [TranslationKeys.ProfilePhotoUploadHint] = "Click to upload a photo",
        [TranslationKeys.ProfilePhotoChangeHint] = "Click to change photo",
        [TranslationKeys.ProfilePhotoUploadButton] = "Upload photo",
        [TranslationKeys.ProfilePhotoRemove] = "Remove photo",
        [TranslationKeys.ProfilePhotoFilePickerTitle] = "Select profile photo",
        [TranslationKeys.ProfilePhotoFileType] = "Images",
        [TranslationKeys.ProfilePhotoUnsupportedFormat] = "Unsupported image format. Use JPEG, PNG, or WebP.",
        [TranslationKeys.ProfilePhotoFileTooLarge] = "Image is too large. Maximum size is 15 MB.",
        [TranslationKeys.ProfilePhotoUnreadable] = "The selected image could not be read.",
        [TranslationKeys.ProfilePhotoMissingOnDisk] = "The profile photo file is missing and was cleared.",
        [TranslationKeys.ExportPdf] = "Export PDF",
        [TranslationKeys.Export] = "Export",
        [TranslationKeys.ExportCv] = "Export CV",
        [TranslationKeys.ExportSaveDialogTitle] = "Export CV",
        [TranslationKeys.ExportSaveDialogTitleFormat] = "Export CV as {0}",
        [TranslationKeys.ExportPdfFileType] = "PDF files",
        [TranslationKeys.ExportDocxFileType] = "Word documents",
        [TranslationKeys.ExportOdtFileType] = "OpenDocument files",
        [TranslationKeys.ExportRtfFileType] = "Rich Text files",
        [TranslationKeys.ExportHtmlFileType] = "HTML files",
        [TranslationKeys.ExportMarkdownFileType] = "Markdown files",
        [TranslationKeys.ExportTxtFileType] = "Plain text files",
        [TranslationKeys.ExportLatexFileType] = "LaTeX files",
        [TranslationKeys.ExportRevitaeJsonFileType] = "ReVitae JSON files",
        [TranslationKeys.ExportJsonResumeFileType] = "JSON Resume files",
        [TranslationKeys.ExportYamlFileType] = "YAML files",
        [TranslationKeys.ExportEuropassXmlFileType] = "Europass XML files",
        [TranslationKeys.ExportHrXmlFileType] = "HR-XML files",
        [TranslationKeys.ExportCsvFileType] = "CSV files",
        [TranslationKeys.ExportTsvFileType] = "TSV files",
        [TranslationKeys.ExportFailed] = "The CV could not be exported. Please try again.",
        [TranslationKeys.ExportFailedFormat] = "The CV could not be exported as {0}. Please try again.",
        [TranslationKeys.ExportModalTitle] = "Export CV",
        [TranslationKeys.ExportModalSubtitle] = "Choose a file format for your download.",
        [TranslationKeys.ExportModalClose] = "Close",
        [TranslationKeys.ExportCategoryDocuments] = "Documents",
        [TranslationKeys.ExportCategoryWebAndText] = "Web & text",
        [TranslationKeys.ExportCategoryStructured] = "Structured data",
        [TranslationKeys.ExportFormatPdf] = "PDF",
        [TranslationKeys.ExportFormatPdfHint] = "Best for sharing and printing",
        [TranslationKeys.ExportFormatDocx] = "Word",
        [TranslationKeys.ExportFormatOdt] = "OpenDocument",
        [TranslationKeys.ExportFormatRtf] = "Rich Text",
        [TranslationKeys.ExportFormatHtml] = "HTML",
        [TranslationKeys.ExportFormatMarkdown] = "Markdown",
        [TranslationKeys.ExportFormatTxt] = "Plain text",
        [TranslationKeys.ExportFormatLatex] = "LaTeX",
        [TranslationKeys.ExportFormatRevitaeJson] = "ReVitae JSON",
        [TranslationKeys.ExportFormatJsonResume] = "JSON Resume",
        [TranslationKeys.ExportFormatYaml] = "YAML",
        [TranslationKeys.ExportFormatEuropassXml] = "Europass XML",
        [TranslationKeys.ExportFormatHrXml] = "HR-XML",
        [TranslationKeys.ExportFormatCsv] = "CSV",
        [TranslationKeys.ExportFormatTsv] = "TSV",
        [TranslationKeys.ExportFormatRecommended] = "Recommended",
        [TranslationKeys.ExportOpenFile] = "Open file",
        [TranslationKeys.ExportShowInFolder] = "Show in folder",
        [TranslationKeys.Preview] = "Preview",
        [TranslationKeys.PreviewExpandTitle] = "Expanded preview",
        [TranslationKeys.Setup] = "Setup",
        [TranslationKeys.SetupAbout] = "About",
        [TranslationKeys.SetupAppName] = "ReVitae",
        [TranslationKeys.SetupVersion] = "Version",
        [TranslationKeys.SetupEarlyPreview] = "Early preview",
        [TranslationKeys.Templates] = "Templates",
        [TranslationKeys.Close] = "Close",
        [TranslationKeys.Language] = "Language",
        [TranslationKeys.Selected] = "Selected",
        [TranslationKeys.ClassicSidebar] = "Classic Sidebar",
        [TranslationKeys.ClassicSidebarDescription] = "Light sidebar with contact details and a clean content area.",
        [TranslationKeys.ModernSidebar] = "Modern Sidebar",
        [TranslationKeys.ModernSidebarDescription] = "Compact sidebar with a dark name band and focused content.",
        [TranslationKeys.CleanTopHeader] = "Clean Top Header",
        [TranslationKeys.CleanTopHeaderDescription] = "Safe default with a full-width color header and simple sections.",
        [TranslationKeys.DarkSidebarAccent] = "Dark Sidebar Accent",
        [TranslationKeys.DarkSidebarAccentDescription] = "Dark sidebar, colored header, and stronger visual personality.",
        [TranslationKeys.CenteredMinimal] = "Centered Minimal",
        [TranslationKeys.CenteredMinimalDescription] = "Single-column layout with centered name, boxed summary, and dark contact bar.",
        [TranslationKeys.PhotoLeftBand] = "Photo Left Band",
        [TranslationKeys.PhotoLeftBandDescription] = "Portrait on the left, name on the right, and a full-width summary band.",
        [TranslationKeys.ExecutiveBlueSidebar] = "Executive Blue Sidebar",
        [TranslationKeys.ExecutiveBlueSidebarDescription] = "Gray sidebar with navy accents, circular photo, and structured main column.",
        [TranslationKeys.PeachDesigner] = "Peach Designer",
        [TranslationKeys.PeachDesignerDescription] = "Peach header contact card, rounded gray sidebar, and warm accent bars.",
        [TranslationKeys.NavyProfileSplit] = "Navy Profile Split",
        [TranslationKeys.NavyProfileSplitDescription] = "Navy header with orange section titles and a two-column experience layout.",
        [TranslationKeys.ForestGreenSidebar] = "Forest Green Sidebar",
        [TranslationKeys.ForestGreenSidebarDescription] = "Forest-green name blocks, rectangular photo, and sidebar contact details.",
        [TranslationKeys.YellowSkillDots] = "Yellow Skill Dots",
        [TranslationKeys.YellowSkillDotsDescription] = "Yellow accent squares, right-column photo, and dotted skill proficiency rows.",
        [TranslationKeys.RoyalBlueSidebar] = "Royal Blue Sidebar",
        [TranslationKeys.RoyalBlueSidebarDescription] = "Full-height royal-blue sidebar with a dark header band and circular photo.",
        [TranslationKeys.OrangeTimeline] = "Orange Timeline",
        [TranslationKeys.OrangeTimelineDescription] = "Single-column résumé with an orange vertical timeline and circular photo header.",
        [TranslationKeys.BlueAccentSummary] = "Blue Accent Summary",
        [TranslationKeys.BlueAccentSummaryDescription] = "Blue accent bar, bordered summary box, and photo aligned to the header.",
        [TranslationKeys.PillHeaderSplit] = "Pill Header Split",
        [TranslationKeys.PillHeaderSplitDescription] = "Circular photo with a rounded contact pill and a two-column skills layout.",
        [TranslationKeys.NavyOverlapPhoto] = "Navy Overlap Photo",
        [TranslationKeys.NavyOverlapPhotoDescription] = "Navy header band with an overlapping circular photo and split columns below.",
        [TranslationKeys.Summary] = "Summary",
        [TranslationKeys.Contact] = "Contact",
        [TranslationKeys.ContactLinks] = "Contact Links",
        [TranslationKeys.Profile] = "Profile",
        [TranslationKeys.Digital] = "Digital",
        [TranslationKeys.Links] = "Links",
        [TranslationKeys.Objective] = "Objective",
        [TranslationKeys.Online] = "Online",
        [TranslationKeys.ExportFixValidation] = "Fix validation errors before exporting.",
        [TranslationKeys.ExportFilePickerUnavailable] = "Unable to open the file picker.",
        [TranslationKeys.ExportedPdfTo] = "Exported PDF to {0}.",
        [TranslationKeys.ExportedTo] = "Exported to {0}.",
        [TranslationKeys.ValidationFirstNameRequired] = "First name is required.",
        [TranslationKeys.ValidationLastNameRequired] = "Last name is required.",
        [TranslationKeys.ValidationEmailRequired] = "Email is required.",
        [TranslationKeys.ValidationFirstNameMax] = "First name must be 80 characters or fewer.",
        [TranslationKeys.ValidationLastNameMax] = "Last name must be 80 characters or fewer.",
        [TranslationKeys.ValidationProfessionalTitleMax] = "Professional title must be 120 characters or fewer.",
        [TranslationKeys.ValidationEmailMax] = "Email must be 160 characters or fewer.",
        [TranslationKeys.ValidationPhoneMax] = "Phone must be 40 characters or fewer.",
        [TranslationKeys.ValidationLocationMax] = "Location must be 120 characters or fewer.",
        [TranslationKeys.ValidationLinkedInUrlMax] = "LinkedIn URL must be 240 characters or fewer.",
        [TranslationKeys.ValidationPortfolioUrlMax] = "Portfolio / website URL must be 240 characters or fewer.",
        [TranslationKeys.ValidationGitHubUrlMax] = "GitHub URL must be 240 characters or fewer.",
        [TranslationKeys.ValidationShortSummaryMax] = "Short summary must be 800 characters or fewer.",
        [TranslationKeys.ValidationEmailFormat] = "Email must be a valid email address.",
        [TranslationKeys.ValidationLinkedInUrlFormat] = "LinkedIn URL must be a valid http or https URL.",
        [TranslationKeys.ValidationPortfolioUrlFormat] = "Portfolio / website URL must be a valid http or https URL.",
        [TranslationKeys.ValidationGitHubUrlFormat] = "GitHub URL must be a valid http or https URL.",
        [TranslationKeys.WorkExperience] = "Work Experience",
        [TranslationKeys.WorkExperienceEmptyHint] = "Add your most recent role first. You can reorder entries later.",
        [TranslationKeys.WorkExperienceAdd] = "Add experience",
        [TranslationKeys.WorkExperienceDuplicate] = "Duplicate",
        [TranslationKeys.WorkExperienceRemove] = "Remove",
        [TranslationKeys.WorkExperienceSortByDate] = "Sort by date (newest first)",
        [TranslationKeys.WorkExperienceJobTitle] = "Job title",
        [TranslationKeys.WorkExperienceCompany] = "Company",
        [TranslationKeys.WorkExperienceLocation] = "Location",
        [TranslationKeys.WorkExperienceEmploymentType] = "Employment type",
        [TranslationKeys.WorkExperienceStartDate] = "Start date",
        [TranslationKeys.WorkExperienceEndDate] = "End date",
        [TranslationKeys.WorkExperienceStartMonth] = "Start month",
        [TranslationKeys.WorkExperienceStartYear] = "Start year",
        [TranslationKeys.WorkExperienceEndMonth] = "End month",
        [TranslationKeys.WorkExperienceEndYear] = "End year",
        [TranslationKeys.WorkExperienceCurrentlyWorking] = "Currently working here",
        [TranslationKeys.WorkExperienceDescription] = "Description",
        [TranslationKeys.WorkExperienceAchievements] = "Achievements",
        [TranslationKeys.WorkExperienceTechnologies] = "Technologies",
        [TranslationKeys.WorkExperienceCompanyUrl] = "Company URL",
        [TranslationKeys.WorkExperiencePresent] = "Present",
        [TranslationKeys.WorkExperienceDragToReorder] = "Drag to reorder",
        [TranslationKeys.WorkExperienceExpand] = "Expand entry",
        [TranslationKeys.WorkExperienceCollapse] = "Collapse entry",
        [TranslationKeys.WorkExperienceValidationErrors] = "{0} errors",
        [TranslationKeys.EmploymentTypeFullTime] = "Full-time",
        [TranslationKeys.EmploymentTypePartTime] = "Part-time",
        [TranslationKeys.EmploymentTypeContract] = "Contract",
        [TranslationKeys.EmploymentTypeFreelance] = "Freelance",
        [TranslationKeys.EmploymentTypeInternship] = "Internship",
        [TranslationKeys.PreviewWorkExperience] = "Work Experience",
        [TranslationKeys.PreviewAchievements] = "Achievements",
        [TranslationKeys.PreviewTechnologies] = "Technologies",
        [TranslationKeys.ExpandSection] = "Expand section",
        [TranslationKeys.CollapseSection] = "Collapse section",
        [TranslationKeys.ValidationWorkExperienceJobTitleRequired] = "Job title is required.",
        [TranslationKeys.ValidationWorkExperienceJobTitleMax] = "Job title must be 120 characters or fewer.",
        [TranslationKeys.ValidationWorkExperienceCompanyRequired] = "Company is required.",
        [TranslationKeys.ValidationWorkExperienceCompanyMax] = "Company must be 160 characters or fewer.",
        [TranslationKeys.ValidationWorkExperienceLocationMax] = "Location must be 120 characters or fewer.",
        [TranslationKeys.ValidationWorkExperienceEmploymentTypeRequired] = "Employment type is required.",
        [TranslationKeys.ValidationWorkExperienceEmploymentTypeInvalid] = "Employment type must be a supported value.",
        [TranslationKeys.ValidationWorkExperienceStartMonthRequired] = "Start month is required.",
        [TranslationKeys.ValidationWorkExperienceStartMonthInvalid] = "Start month must be between 1 and 12.",
        [TranslationKeys.ValidationWorkExperienceStartYearRequired] = "Start year is required.",
        [TranslationKeys.ValidationWorkExperienceStartYearInvalid] = "Start year must be between 1950 and 2100.",
        [TranslationKeys.ValidationWorkExperienceEndMonthRequired] = "End month is required.",
        [TranslationKeys.ValidationWorkExperienceEndMonthInvalid] = "End month must be between 1 and 12.",
        [TranslationKeys.ValidationWorkExperienceEndYearRequired] = "End year is required.",
        [TranslationKeys.ValidationWorkExperienceEndYearInvalid] = "End year must be between 1950 and 2100.",
        [TranslationKeys.ValidationWorkExperienceDescriptionMax] = "Description must be 2000 characters or fewer.",
        [TranslationKeys.ValidationWorkExperienceAchievementsMax] = "Achievements must be 2000 characters or fewer.",
        [TranslationKeys.ValidationWorkExperienceTechnologiesMax] = "Technologies must be 500 characters or fewer.",
        [TranslationKeys.ValidationWorkExperienceCompanyUrlMax] = "Company URL must be 240 characters or fewer.",
        [TranslationKeys.ValidationWorkExperienceCompanyUrlFormat] = "Company URL must be a valid http or https URL.",
        [TranslationKeys.ValidationWorkExperienceStartAfterEnd] = "Start date must not be after end date.",
        [TranslationKeys.Education] = "Education",
        [TranslationKeys.EducationEmptyHint] = "Add your most recent qualification first. You can reorder entries later.",
        [TranslationKeys.EducationAdd] = "Add education",
        [TranslationKeys.EducationDuplicate] = "Duplicate",
        [TranslationKeys.EducationRemove] = "Remove",
        [TranslationKeys.EducationSortByDate] = "Sort by date (newest first)",
        [TranslationKeys.EducationInstitution] = "Institution",
        [TranslationKeys.EducationDegree] = "Degree",
        [TranslationKeys.EducationFieldOfStudy] = "Field of study",
        [TranslationKeys.EducationLocation] = "Location",
        [TranslationKeys.EducationDegreeType] = "Degree type",
        [TranslationKeys.EducationStartDate] = "Start date",
        [TranslationKeys.EducationEndDate] = "End date",
        [TranslationKeys.EducationStartMonth] = "Start month",
        [TranslationKeys.EducationStartYear] = "Start year",
        [TranslationKeys.EducationEndMonth] = "End month",
        [TranslationKeys.EducationEndYear] = "End year",
        [TranslationKeys.EducationCurrentlyStudying] = "Currently studying here",
        [TranslationKeys.EducationGrade] = "Grade",
        [TranslationKeys.EducationDescription] = "Description",
        [TranslationKeys.EducationInstitutionUrl] = "Institution URL",
        [TranslationKeys.EducationPresent] = "Present",
        [TranslationKeys.EducationDragToReorder] = "Drag to reorder",
        [TranslationKeys.EducationExpand] = "Expand entry",
        [TranslationKeys.EducationCollapse] = "Collapse entry",
        [TranslationKeys.EducationValidationErrors] = "{0} errors",
        [TranslationKeys.DegreeTypeHighSchool] = "High school",
        [TranslationKeys.DegreeTypeAssociate] = "Associate",
        [TranslationKeys.DegreeTypeBachelor] = "Bachelor",
        [TranslationKeys.DegreeTypeMaster] = "Master",
        [TranslationKeys.DegreeTypeDoctorate] = "Doctorate",
        [TranslationKeys.DegreeTypeCertificate] = "Certificate",
        [TranslationKeys.DegreeTypeOther] = "Other",
        [TranslationKeys.PreviewEducation] = "Education",
        [TranslationKeys.PreviewGrade] = "Grade",
        [TranslationKeys.PreviewFieldOfStudy] = "Field of study",
        [TranslationKeys.ValidationEducationInstitutionRequired] = "Institution is required.",
        [TranslationKeys.ValidationEducationInstitutionMax] = "Institution must be 160 characters or fewer.",
        [TranslationKeys.ValidationEducationDegreeRequired] = "Degree is required.",
        [TranslationKeys.ValidationEducationDegreeMax] = "Degree must be 160 characters or fewer.",
        [TranslationKeys.ValidationEducationFieldOfStudyMax] = "Field of study must be 160 characters or fewer.",
        [TranslationKeys.ValidationEducationLocationMax] = "Location must be 120 characters or fewer.",
        [TranslationKeys.ValidationEducationDegreeTypeRequired] = "Degree type is required.",
        [TranslationKeys.ValidationEducationDegreeTypeInvalid] = "Degree type must be a supported value.",
        [TranslationKeys.ValidationEducationStartMonthRequired] = "Start month is required.",
        [TranslationKeys.ValidationEducationStartMonthInvalid] = "Start month must be between 1 and 12.",
        [TranslationKeys.ValidationEducationStartYearRequired] = "Start year is required.",
        [TranslationKeys.ValidationEducationStartYearInvalid] = "Start year must be between 1950 and 2100.",
        [TranslationKeys.ValidationEducationEndMonthRequired] = "End month is required.",
        [TranslationKeys.ValidationEducationEndMonthInvalid] = "End month must be between 1 and 12.",
        [TranslationKeys.ValidationEducationEndYearRequired] = "End year is required.",
        [TranslationKeys.ValidationEducationEndYearInvalid] = "End year must be between 1950 and 2100.",
        [TranslationKeys.ValidationEducationGradeMax] = "Grade must be 80 characters or fewer.",
        [TranslationKeys.ValidationEducationDescriptionMax] = "Description must be 2000 characters or fewer.",
        [TranslationKeys.ValidationEducationInstitutionUrlMax] = "Institution URL must be 240 characters or fewer.",
        [TranslationKeys.ValidationEducationInstitutionUrlFormat] = "Institution URL must be a valid http or https URL.",
        [TranslationKeys.ValidationEducationStartAfterEnd] = "Start date must not be after end date.",
        [TranslationKeys.Skills] = "Skills",
        [TranslationKeys.SkillsEmptyHint] = "Group related skills together. You can reorder groups later.",
        [TranslationKeys.SkillsAdd] = "Add skill group",
        [TranslationKeys.SkillsDuplicate] = "Duplicate",
        [TranslationKeys.SkillsRemove] = "Remove",
        [TranslationKeys.SkillsCategory] = "Category",
        [TranslationKeys.SkillsSkillName] = "Skill",
        [TranslationKeys.SkillsProficiency] = "Proficiency",
        [TranslationKeys.SkillsYearsOfExperience] = "Years",
        [TranslationKeys.SkillsAddSkill] = "Add skill",
        [TranslationKeys.SkillsAddFromList] = "Add from list",
        [TranslationKeys.SkillsBulkSkills] = "Bulk add skills",
        [TranslationKeys.SkillsBulkSkillsPlaceholder] = "C#, TypeScript, Git or one skill per line",
        [TranslationKeys.SkillsRemoveSkill] = "Remove skill",
        [TranslationKeys.SkillsDragToReorder] = "Drag to reorder",
        [TranslationKeys.SkillsDragSkillToMove] = "Drag skill to move between groups",
        [TranslationKeys.SkillsExpand] = "Expand entry",
        [TranslationKeys.SkillsCollapse] = "Collapse entry",
        [TranslationKeys.SkillsValidationErrors] = "{0} errors",
        [TranslationKeys.ProficiencyBeginner] = "Beginner",
        [TranslationKeys.ProficiencyIntermediate] = "Intermediate",
        [TranslationKeys.ProficiencyAdvanced] = "Advanced",
        [TranslationKeys.ProficiencyExpert] = "Expert",
        [TranslationKeys.PreviewSkills] = "Skills",
        [TranslationKeys.PreviewYearsSuffix] = "yrs",
        [TranslationKeys.ValidationSkillsCategoryRequired] = "Category is required.",
        [TranslationKeys.ValidationSkillsCategoryMax] = "Category must be 120 characters or fewer.",
        [TranslationKeys.ValidationSkillsSkillNameRequired] = "Skill name is required.",
        [TranslationKeys.ValidationSkillsSkillNameMax] = "Skill name must be 80 characters or fewer.",
        [TranslationKeys.ValidationSkillsAtLeastOneRequired] = "Add at least one skill to this group.",
        [TranslationKeys.ValidationSkillsProficiencyRequired] = "Proficiency is required.",
        [TranslationKeys.ValidationSkillsProficiencyInvalid] = "Proficiency must be a supported value.",
        [TranslationKeys.ValidationSkillsYearsOfExperienceInvalid] = "Years of experience must be between 0 and 60.",
        [TranslationKeys.ValidationSkillsDuplicateInGroup] = "This skill is already listed in this group.",
        [TranslationKeys.ValidationSkillsBulkSkillsMax] = "Bulk skills text must be 1000 characters or fewer.",
        [TranslationKeys.Languages] = "Languages",
        [TranslationKeys.LanguagesEmptyHint] = "Add your strongest languages first. You can reorder entries later.",
        [TranslationKeys.LanguagesAdd] = "Add language",
        [TranslationKeys.LanguagesDuplicate] = "Duplicate",
        [TranslationKeys.LanguagesRemove] = "Remove",
        [TranslationKeys.LanguagesLanguage] = "Language",
        [TranslationKeys.LanguagesProficiency] = "Proficiency",
        [TranslationKeys.LanguagesCefrLevel] = "CEFR level",
        [TranslationKeys.LanguagesCertificate] = "Certificate or note",
        [TranslationKeys.LanguagesReading] = "Reading",
        [TranslationKeys.LanguagesWriting] = "Writing",
        [TranslationKeys.LanguagesSpeaking] = "Speaking",
        [TranslationKeys.LanguagesListening] = "Listening",
        [TranslationKeys.LanguagesSubSkills] = "Sub-skills",
        [TranslationKeys.LanguagesCefrNone] = "Not specified",
        [TranslationKeys.LanguagesProficiencyNone] = "Not specified",
        [TranslationKeys.LanguagesDragToReorder] = "Drag to reorder",
        [TranslationKeys.LanguagesExpand] = "Expand entry",
        [TranslationKeys.LanguagesCollapse] = "Collapse entry",
        [TranslationKeys.LanguagesValidationErrors] = "{0} errors",
        [TranslationKeys.LanguageProficiencyElementary] = "Elementary",
        [TranslationKeys.LanguageProficiencyIntermediate] = "Intermediate",
        [TranslationKeys.LanguageProficiencyAdvanced] = "Advanced",
        [TranslationKeys.LanguageProficiencyFluent] = "Fluent",
        [TranslationKeys.LanguageProficiencyNative] = "Native",
        [TranslationKeys.CefrA1] = "A1",
        [TranslationKeys.CefrA2] = "A2",
        [TranslationKeys.CefrB1] = "B1",
        [TranslationKeys.CefrB2] = "B2",
        [TranslationKeys.CefrC1] = "C1",
        [TranslationKeys.CefrC2] = "C2",
        [TranslationKeys.PreviewLanguages] = "Languages",
        [TranslationKeys.PreviewReading] = "Reading",
        [TranslationKeys.PreviewWriting] = "Writing",
        [TranslationKeys.PreviewSpeaking] = "Speaking",
        [TranslationKeys.PreviewListening] = "Listening",
        [TranslationKeys.ValidationLanguagesLanguageRequired] = "Language is required.",
        [TranslationKeys.ValidationLanguagesLanguageMax] = "Language must be 80 characters or fewer.",
        [TranslationKeys.ValidationLanguagesProficiencyRequired] = "Proficiency is required.",
        [TranslationKeys.ValidationLanguagesProficiencyInvalid] = "Proficiency must be a supported value.",
        [TranslationKeys.ValidationLanguagesCefrInvalid] = "CEFR level must be a supported value.",
        [TranslationKeys.ValidationLanguagesCertificateMax] = "Certificate or note must be 120 characters or fewer.",
        [TranslationKeys.ValidationLanguagesDuplicateLanguage] = "This language is already listed.",
        [TranslationKeys.Certificates] = "Certificates",
        [TranslationKeys.CertificatesEmptyHint] = "Add your most relevant certifications first. You can reorder entries later.",
        [TranslationKeys.CertificatesAdd] = "Add certificate",
        [TranslationKeys.CertificatesDuplicate] = "Duplicate",
        [TranslationKeys.CertificatesRemove] = "Remove",
        [TranslationKeys.CertificatesSortByDate] = "Sort by date (newest first)",
        [TranslationKeys.CertificatesName] = "Certificate name",
        [TranslationKeys.CertificatesIssuer] = "Issuing organization",
        [TranslationKeys.CertificatesIssueDate] = "Issue date",
        [TranslationKeys.CertificatesExpirationDate] = "Expiration date",
        [TranslationKeys.CertificatesIssueMonth] = "Issue month",
        [TranslationKeys.CertificatesIssueYear] = "Issue year",
        [TranslationKeys.CertificatesExpirationMonth] = "Expiration month",
        [TranslationKeys.CertificatesExpirationYear] = "Expiration year",
        [TranslationKeys.CertificatesCredentialId] = "Credential ID",
        [TranslationKeys.CertificatesCredentialUrl] = "Credential URL",
        [TranslationKeys.CertificatesDescription] = "Description or note",
        [TranslationKeys.CertificatesDragToReorder] = "Drag to reorder",
        [TranslationKeys.CertificatesExpand] = "Expand entry",
        [TranslationKeys.CertificatesCollapse] = "Collapse entry",
        [TranslationKeys.CertificatesValidationErrors] = "{0} errors",
        [TranslationKeys.PreviewCertificates] = "Certificates",
        [TranslationKeys.PreviewValidUntil] = "Valid until",
        [TranslationKeys.PreviewCredentialId] = "Credential ID",
        [TranslationKeys.PreviewCredentialUrl] = "Credential URL",
        [TranslationKeys.ValidationCertificatesNameRequired] = "Certificate name is required.",
        [TranslationKeys.ValidationCertificatesNameMax] = "Certificate name must be 160 characters or fewer.",
        [TranslationKeys.ValidationCertificatesIssuerRequired] = "Issuing organization is required.",
        [TranslationKeys.ValidationCertificatesIssuerMax] = "Issuing organization must be 160 characters or fewer.",
        [TranslationKeys.ValidationCertificatesIssueMonthRequired] = "Issue month is required.",
        [TranslationKeys.ValidationCertificatesIssueMonthInvalid] = "Issue month must be between 1 and 12.",
        [TranslationKeys.ValidationCertificatesIssueYearRequired] = "Issue year is required.",
        [TranslationKeys.ValidationCertificatesIssueYearInvalid] = "Issue year must be between 1950 and 2100.",
        [TranslationKeys.ValidationCertificatesExpirationMonthInvalid] = "Expiration month must be between 1 and 12.",
        [TranslationKeys.ValidationCertificatesExpirationYearInvalid] = "Expiration year must be between 1950 and 2100.",
        [TranslationKeys.ValidationCertificatesCredentialIdMax] = "Credential ID must be 80 characters or fewer.",
        [TranslationKeys.ValidationCertificatesCredentialUrlMax] = "Credential URL must be 240 characters or fewer.",
        [TranslationKeys.ValidationCertificatesCredentialUrlFormat] = "Credential URL must be a valid http or https URL.",
        [TranslationKeys.ValidationCertificatesDescriptionMax] = "Description or note must be 500 characters or fewer.",
        [TranslationKeys.ValidationCertificatesIssueAfterExpiration] = "Issue date must not be after expiration date.",
        [TranslationKeys.Projects] = "Projects",
        [TranslationKeys.ProjectsEmptyHint] = "Add your strongest projects first. You can reorder entries later.",
        [TranslationKeys.ProjectsAdd] = "Add project",
        [TranslationKeys.ProjectsDuplicate] = "Duplicate",
        [TranslationKeys.ProjectsRemove] = "Remove",
        [TranslationKeys.ProjectsSortByDate] = "Sort by date (newest first)",
        [TranslationKeys.ProjectsName] = "Project name",
        [TranslationKeys.ProjectsRole] = "Role",
        [TranslationKeys.ProjectsOrganization] = "Organization or context",
        [TranslationKeys.ProjectsStartDate] = "Start date",
        [TranslationKeys.ProjectsEndDate] = "End date",
        [TranslationKeys.ProjectsStartMonth] = "Start month",
        [TranslationKeys.ProjectsStartYear] = "Start year",
        [TranslationKeys.ProjectsEndMonth] = "End month",
        [TranslationKeys.ProjectsEndYear] = "End year",
        [TranslationKeys.ProjectsCurrentlyActive] = "Currently active",
        [TranslationKeys.ProjectsProjectUrl] = "Project URL",
        [TranslationKeys.ProjectsTechnologyName] = "Technology",
        [TranslationKeys.ProjectsAddTechnology] = "Add technology",
        [TranslationKeys.ProjectsBulkTechnologies] = "Bulk technologies",
        [TranslationKeys.ProjectsBulkTechnologiesPlaceholder] = "Enter technologies separated by commas or new lines",
        [TranslationKeys.ProjectsAddFromList] = "Add from list",
        [TranslationKeys.ProjectsRemoveTechnology] = "Remove technology",
        [TranslationKeys.ProjectsHighlights] = "Highlights",
        [TranslationKeys.ProjectsDescription] = "Description",
        [TranslationKeys.ProjectsDragToReorder] = "Drag to reorder",
        [TranslationKeys.ProjectsExpand] = "Expand entry",
        [TranslationKeys.ProjectsCollapse] = "Collapse entry",
        [TranslationKeys.ProjectsValidationErrors] = "{0} errors",
        [TranslationKeys.ProjectsPresent] = "Present",
        [TranslationKeys.PreviewProjects] = "Projects",
        [TranslationKeys.PreviewHighlights] = "Highlights",
        [TranslationKeys.ValidationProjectsNameRequired] = "Project name is required.",
        [TranslationKeys.ValidationProjectsNameMax] = "Project name must be 160 characters or fewer.",
        [TranslationKeys.ValidationProjectsRoleMax] = "Role must be 120 characters or fewer.",
        [TranslationKeys.ValidationProjectsOrganizationMax] = "Organization or context must be 160 characters or fewer.",
        [TranslationKeys.ValidationProjectsStartMonthInvalid] = "Start month must be between 1 and 12.",
        [TranslationKeys.ValidationProjectsStartYearInvalid] = "Start year must be between 1950 and 2100.",
        [TranslationKeys.ValidationProjectsEndMonthInvalid] = "End month must be between 1 and 12.",
        [TranslationKeys.ValidationProjectsEndYearInvalid] = "End year must be between 1950 and 2100.",
        [TranslationKeys.ValidationProjectsProjectUrlMax] = "Project URL must be 240 characters or fewer.",
        [TranslationKeys.ValidationProjectsProjectUrlFormat] = "Project URL must be a valid http or https URL.",
        [TranslationKeys.ValidationProjectsHighlightsMax] = "Highlights must be 2000 characters or fewer.",
        [TranslationKeys.ValidationProjectsDescriptionMax] = "Description must be 2000 characters or fewer.",
        [TranslationKeys.ValidationProjectsTechnologyNameRequired] = "Technology name is required.",
        [TranslationKeys.ValidationProjectsTechnologyNameMax] = "Technology name must be 80 characters or fewer.",
        [TranslationKeys.ValidationProjectsDuplicateTechnology] = "This technology is already listed in this project.",
        [TranslationKeys.ValidationProjectsBulkTechnologiesMax] = "Bulk technologies text must be 1000 characters or fewer.",
        [TranslationKeys.ValidationProjectsStartAfterEnd] = "Start date must not be after end date.",
        [TranslationKeys.CustomLinks] = "Links",
        [TranslationKeys.CustomLinksEmptyHint] = "Add links to profiles, portfolios, or publications that are not already in your main contact details.",
        [TranslationKeys.CustomLinksAdd] = "Add link",
        [TranslationKeys.CustomLinksDuplicate] = "Duplicate",
        [TranslationKeys.CustomLinksRemove] = "Remove",
        [TranslationKeys.CustomLinksLabel] = "Label",
        [TranslationKeys.CustomLinksUrl] = "URL",
        [TranslationKeys.CustomLinksNote] = "Note",
        [TranslationKeys.CustomLinksDragToReorder] = "Drag to reorder",
        [TranslationKeys.CustomLinksExpand] = "Expand entry",
        [TranslationKeys.CustomLinksCollapse] = "Collapse entry",
        [TranslationKeys.CustomLinksValidationErrors] = "{0} errors",
        [TranslationKeys.PreviewCustomLinks] = "Links",
        [TranslationKeys.ValidationLinksLabelRequired] = "Label is required.",
        [TranslationKeys.ValidationLinksLabelMax] = "Label must be 80 characters or fewer.",
        [TranslationKeys.ValidationLinksUrlRequired] = "URL is required.",
        [TranslationKeys.ValidationLinksUrlMax] = "URL must be 240 characters or fewer.",
        [TranslationKeys.ValidationLinksUrlFormat] = "URL must be a valid http or https URL.",
        [TranslationKeys.ValidationLinksNoteMax] = "Note must be 120 characters or fewer.",
        [TranslationKeys.ValidationLinksDuplicateUrl] = "This URL is already listed.",
        [TranslationKeys.AdditionalInformation] = "Additional Information",
        [TranslationKeys.AdditionalInformationEmptyHint] = "Use this section for interests, volunteering, publications, or other notes that do not belong elsewhere.",
        [TranslationKeys.AdditionalInformationContent] = "Content",
        [TranslationKeys.AdditionalInformationValidationErrors] = "{0} errors",
        [TranslationKeys.PreviewAdditionalInformation] = "Additional Information",
        [TranslationKeys.ValidationAdditionalInformationContentMax] = "Content must be 3000 characters or fewer.",
        [TranslationKeys.IntroTitle] = "Welcome to ReVitae",
        [TranslationKeys.IntroSubtitle] = "Create a new CV from scratch or import an existing file to get started faster.",
        [TranslationKeys.IntroHelper] =
            "Works with PDF, Word, OpenDocument, RTF, text, Markdown, HTML, JSON, XML, and other common CV files. "
            + "Scanned or image‑only PDFs are not supported.",
        [TranslationKeys.IntroCreateNew] = "Create new CV",
        [TranslationKeys.IntroImportPdf] = "Import existing CV",
        [TranslationKeys.IntroReadingPdf] = "Reading document…",
        [TranslationKeys.IntroParsingCv] = "Parsing CV…",
        [TranslationKeys.IntroImportRetry] = "Try import again",
        [TranslationKeys.ReplaceCvConfirmTitle] = "Replace current CV?",
        [TranslationKeys.ReplaceCvConfirmMessage] =
            "Importing a new file will replace all current CV data. Do you want to continue?",
        [TranslationKeys.NewCvConfirmTitle] = "Discard changes?",
        [TranslationKeys.NewCvConfirmMessage] =
            "Creating a new CV will discard all current data. Do you want to continue?",
        [TranslationKeys.UploadCvFilePickerTitle] = "Upload CV",
        [TranslationKeys.ImportCvFilePickerTitle] = "Import CV",
        [TranslationKeys.ImportPdfFileType] = "Supported CV files",
        [TranslationKeys.ImportErrorFileNotFound] = "The selected file could not be found.",
        [TranslationKeys.ImportErrorEmptyPdf] = "This PDF does not contain extractable text.",
        [TranslationKeys.ImportErrorUnreadablePdf] = "The PDF could not be read.",
        [TranslationKeys.ImportErrorPasswordProtected] = "Password-protected documents are not supported.",
        [TranslationKeys.ImportErrorNoStructuredData] = "No usable CV content could be extracted.",
        [TranslationKeys.ImportWarningNoSectionsDetected] = "No CV sections were detected. Content was placed into Additional Information.",
        [TranslationKeys.ImportWarningNameUncertain] = "The candidate name could not be parsed confidently.",
        [TranslationKeys.ImportWarningWorkExperiencePartial] = "Some work experience entries may be incomplete.",
        [TranslationKeys.ImportWarningUnmappedTextAppended] = "Some text could not be mapped and was appended to Additional Information.",
        [TranslationKeys.ImportWarningPersonalLinksDuplicatedSkipped] = "A URL already stored in personal information was skipped in Links.",
        [TranslationKeys.ImportDefaultSkillsCategory] = "General",
        [TranslationKeys.ImportErrorEmptyDocument] = "The file does not contain extractable text.",
        [TranslationKeys.ImportErrorUnreadableDocument] = "The file could not be read.",
        [TranslationKeys.ImportErrorUnsupportedFormat] =
            "This file type is not supported. Export the CV as PDF, DOCX, RTF, or plain text and try again.",
        [TranslationKeys.ImportErrorUnsupportedStructuredFormat] = "The file is recognized, but its structure is not supported.",
        [TranslationKeys.ImportErrorFileTooLarge] = "This file is too large to import. Maximum size is 25 MB.",
        [TranslationKeys.ImportWarningPartialDocumentContent] = "Some document content could not be imported.",
        [TranslationKeys.ImportWarningLatexPartiallyNormalized] = "LaTeX markup was simplified before parsing.",
        [TranslationKeys.ImportWarningTabularMultipleRowsIgnored] = "Only the first row of the table was imported.",
        [TranslationKeys.ImportRunningOcr] = "Recognizing text from image…",
        [TranslationKeys.ImportWarningOcrUsed] = "This file was read using OCR. Please review all fields carefully.",
        [TranslationKeys.ImportErrorOcrUnavailable] = "OCR is not available on this system.",
        [TranslationKeys.ImportErrorOcrFailed] = "Could not recognize text in this image or scan.",
        [TranslationKeys.ImportRasterImageFileType] = "Images (JPEG, PNG, …)",
        [TranslationKeys.ImportForceOcr] = "Import as scan (OCR)"
    };

    private static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> TranslationOverlays =
        new Dictionary<string, IReadOnlyDictionary<string, string>>
        {
            ["sk"] = Overlay("Vytvorte jednoduchý náhľad CV a exportujte plain PDF.", "Nastavenia", "Šablóny", "Jazyk", "Zavrieť", "Meno", "Priezvisko", "Profesijný titul", "Telefón", "Lokalita", "Krátke zhrnutie", "Náhľad", "Vybrané", "Pracovné skúsenosti", "Pridajte najprv poslednú pozíciu. Poradie môžete zmeniť neskôr.", "Rozbaliť náhľad", "Rozšírený náhľad"),
            ["cs"] = Overlay("Vytvořte jednoduchý náhled CV a exportujte plain PDF.", "Nastavení", "Šablony", "Jazyk", "Zavřít", "Jméno", "Příjmení", "Profesní titul", "Telefon", "Lokalita", "Krátké shrnutí", "Náhled", "Vybráno", "Pracovní zkušenosti", "Nejprve přidejte poslední roli. Pořadí můžete změnit později.", "Rozbalit náhled", "Rozšířený náhled"),
            ["es"] = Overlay("Crea una vista previa simple del CV y exporta un PDF básico.", "Configuración", "Plantillas", "Idioma", "Cerrar", "Nombre", "Apellido", "Título profesional", "Teléfono", "Ubicación", "Resumen breve", "Vista previa", "Seleccionado", "Experiencia laboral", "Agrega tu rol más reciente primero. Puedes reordenar después.", "Expandir vista previa", "Vista previa ampliada"),
            ["fr"] = Overlay("Créez un aperçu simple du CV et exportez un PDF léger.", "Configuration", "Modèles", "Langue", "Fermer", "Prénom", "Nom", "Titre professionnel", "Téléphone", "Lieu", "Résumé court", "Aperçu", "Sélectionné", "Expérience professionnelle", "Ajoutez d'abord votre poste le plus récent. Vous pourrez réorganiser ensuite.", "Agrandir l'aperçu", "Aperçu agrandi"),
            ["de"] = Overlay("Erstellen Sie eine einfache CV-Vorschau und exportieren Sie ein schlichtes PDF.", "Einrichtung", "Vorlagen", "Sprache", "Schließen", "Vorname", "Nachname", "Berufsbezeichnung", "Telefon", "Standort", "Kurzprofil", "Vorschau", "Ausgewählt", "Berufserfahrung", "Fügen Sie zuerst Ihre aktuelle Rolle hinzu. Die Reihenfolge können Sie später ändern.", "Vorschau vergrößern", "Erweiterte Vorschau"),
            ["pt"] = Overlay("Crie uma pré-visualização simples do CV e exporte um PDF básico.", "Configuração", "Modelos", "Idioma", "Fechar", "Nome", "Sobrenome", "Título profissional", "Telefone", "Localização", "Resumo curto", "Pré-visualização", "Selecionado", "Experiência profissional", "Adicione primeiro a função mais recente. Você pode reordenar depois.", "Expandir pré-visualização", "Pré-visualização ampliada"),
            ["it"] = Overlay("Crea un'anteprima semplice del CV ed esporta un PDF leggero.", "Configurazione", "Modelli", "Lingua", "Chiudi", "Nome", "Cognome", "Titolo professionale", "Telefono", "Località", "Breve riepilogo", "Anteprima", "Selezionato", "Esperienza lavorativa", "Aggiungi prima il ruolo più recente. Potrai riordinare in seguito.", "Espandi anteprima", "Anteprima ingrandita"),
            ["nl"] = Overlay("Maak een eenvoudige cv-preview en exporteer een eenvoudige PDF.", "Instellingen", "Sjablonen", "Taal", "Sluiten", "Voornaam", "Achternaam", "Functietitel", "Telefoon", "Locatie", "Korte samenvatting", "Voorbeeld", "Geselecteerd", "Werkervaring", "Voeg eerst je meest recente rol toe. Je kunt later herschikken.", "Voorbeeld vergroten", "Uitgevouwen voorbeeld"),
            ["pl"] = Overlay("Utwórz prosty podgląd CV i wyeksportuj lekki PDF.", "Ustawienia", "Szablony", "Język", "Zamknij", "Imię", "Nazwisko", "Tytuł zawodowy", "Telefon", "Lokalizacja", "Krótkie podsumowanie", "Podgląd", "Wybrano", "Doświadczenie zawodowe", "Najpierw dodaj ostatnie stanowisko. Kolejność możesz zmienić później.", "Powiększ podgląd", "Powiększony podgląd"),
            ["uk"] = Overlay("Створіть простий попередній перегляд CV та експортуйте простий PDF.", "Налаштування", "Шаблони", "Мова", "Закрити", "Ім'я", "Прізвище", "Професійний заголовок", "Телефон", "Місцезнаходження", "Короткий опис", "Перегляд", "Вибрано", "Досвід роботи", "Спочатку додайте останню роль. Порядок можна змінити пізніше.", "Розгорнути перегляд", "Розширений перегляд"),
            ["zh-Hans"] = Overlay("创建简单的简历预览并导出基础 PDF。", "设置", "模板", "语言", "关闭", "名", "姓", "职业标题", "电话", "位置", "简短摘要", "预览", "已选择", "工作经历", "请先添加最近的工作。之后可以重新排序。", "展开预览", "展开的预览")
        };

    private readonly IReadOnlyDictionary<string, string> _translations;

    public AppLocalizer(string languageCode)
    {
        LanguageCode = DetectSupportedLanguage(languageCode);
        _translations = BuildTranslations(LanguageCode);
    }

    public string LanguageCode { get; }

    public static AppLocalizer FromSystemCulture()
    {
        return new AppLocalizer(CultureInfo.CurrentUICulture.Name);
    }

    public static string DetectSupportedLanguage(CultureInfo culture)
    {
        return DetectSupportedLanguage(culture.Name);
    }

    public static string DetectSupportedLanguage(string cultureName)
    {
        if (string.IsNullOrWhiteSpace(cultureName))
        {
            return FallbackLanguageCode;
        }

        var normalized = cultureName.Equals("zh", StringComparison.OrdinalIgnoreCase)
            ? "zh-Hans"
            : cultureName;

        if (SupportedLanguages.Any(language => language.Code.Equals(normalized, StringComparison.OrdinalIgnoreCase)))
        {
            return SupportedLanguages.First(language => language.Code.Equals(normalized, StringComparison.OrdinalIgnoreCase)).Code;
        }

        var parent = normalized.Split('-', StringSplitOptions.RemoveEmptyEntries)[0];
        if (parent.Equals("zh", StringComparison.OrdinalIgnoreCase))
        {
            return "zh-Hans";
        }

        var parentMatch = SupportedLanguages.FirstOrDefault(language => language.Code.Equals(parent, StringComparison.OrdinalIgnoreCase));
        return parentMatch?.Code ?? FallbackLanguageCode;
    }

    public string Get(string key)
    {
        return _translations.TryGetValue(key, out var value) ? value : key;
    }

    public string Format(string key, params object[] values)
    {
        return string.Format(CultureInfo.CurrentCulture, Get(key), values);
    }

    public static IReadOnlyDictionary<string, string> GetTranslations(string languageCode)
    {
        return BuildTranslations(DetectSupportedLanguage(languageCode));
    }

    private static IReadOnlyDictionary<string, string> BuildTranslations(string languageCode)
    {
        var translations = new Dictionary<string, string>(EnglishTranslations, StringComparer.Ordinal);
        if (TranslationOverlays.TryGetValue(languageCode, out var overlay))
        {
            foreach (var (key, value) in overlay)
            {
                translations[key] = value;
            }
        }

        return translations;
    }

    private static IReadOnlyDictionary<string, string> Overlay(
        string subtitle,
        string setup,
        string templates,
        string language,
        string close,
        string firstName,
        string lastName,
        string professionalTitle,
        string phone,
        string location,
        string shortSummary,
        string preview,
        string selected,
        string workExperience,
        string workExperienceEmptyHint,
        string openExpandPreview,
        string previewExpandTitle)
    {
        return new Dictionary<string, string>
        {
            [TranslationKeys.HeaderSubtitle] = subtitle,
            [TranslationKeys.OpenSetup] = setup,
            [TranslationKeys.OpenTemplates] = templates,
            [TranslationKeys.OpenExpandPreview] = openExpandPreview,
            [TranslationKeys.Setup] = setup,
            [TranslationKeys.Templates] = templates,
            [TranslationKeys.Language] = language,
            [TranslationKeys.Close] = close,
            [TranslationKeys.FirstName] = firstName,
            [TranslationKeys.LastName] = lastName,
            [TranslationKeys.ProfessionalTitle] = professionalTitle,
            [TranslationKeys.Phone] = phone,
            [TranslationKeys.Location] = location,
            [TranslationKeys.ShortSummary] = shortSummary,
            [TranslationKeys.Preview] = preview,
            [TranslationKeys.PreviewExpandTitle] = previewExpandTitle,
            [TranslationKeys.Selected] = selected,
            [TranslationKeys.WorkExperience] = workExperience,
            [TranslationKeys.WorkExperienceEmptyHint] = workExperienceEmptyHint
        };
    }
}
