using System.Globalization;
using ReVitae.Core.Export;

namespace ReVitae.Core.Localization;

public sealed class AppLocalizer
{
	public const string FallbackLanguageCode = "en";

	public static readonly IReadOnlyList<SupportedLanguage> SupportedLanguages =
	[
		new("en", "English", "English", "🇬🇧"),
		new("es", "Spanish", "Español", "🇪🇸"),
		new("fr", "French", "Français", "🇫🇷"),
		new("de", "German", "Deutsch", "🇩🇪"),
		new("pt", "Portuguese", "Português", "🇵🇹"),
		new("it", "Italian", "Italiano", "🇮🇹"),
		new("nl", "Dutch", "Nederlands", "🇳🇱"),
		new("pl", "Polish", "Polski", "🇵🇱"),
		new("uk", "Ukrainian", "Українська", "🇺🇦"),
		new("zh-Hans", "Chinese Simplified", "简体中文", "🇨🇳"),
		new("sk", "Slovak", "Slovenčina", "🇸🇰"),
		new("cs", "Czech", "Čeština", "🇨🇿")
	];

	private static readonly IReadOnlyDictionary<string, string> EnglishTranslations = new Dictionary<string, string>
	{
		[TranslationKeys.HeaderSubtitle] = "Create a simple CV preview and export a plain PDF.",
		[TranslationKeys.OpenSetup] = "Open setup",
		[TranslationKeys.OpenAbout] = "About",
		[TranslationKeys.OpenUploadCv] = "Upload another CV",
		[TranslationKeys.OpenCreateNewCv] = "Create new CV",
		[TranslationKeys.OpenTemplates] = "Open templates",
		[TranslationKeys.OpenAiSetup] = "Open AI setup",
		[TranslationKeys.Confirm] = "OK",
		[TranslationKeys.Cancel] = "Cancel",
		[TranslationKeys.OpenExpandPreview] = "Expand preview",
		[TranslationKeys.MainPersonalInformation] = "Main / Personal information",
		[TranslationKeys.PersonalInformationValidationErrors] = "{0} errors",
		[TranslationKeys.FirstName] = "First name",
		[TranslationKeys.LastName] = "Last name",
		[TranslationKeys.ProfessionalTitle] = "Professional title",
		[TranslationKeys.Email] = "Email",
		[TranslationKeys.Phone] = "Phone",
		[TranslationKeys.Location] = "Location",
		[TranslationKeys.LinkedInUrl] = "LinkedIn URL",
		[TranslationKeys.PortfolioUrl] = "Portfolio / website URL",
		[TranslationKeys.GitHubUrl] = "GitHub URL",
		[TranslationKeys.ShortSummary] = "Short summary",
		[TranslationKeys.ShortSummaryPlaceholder] = "Write two to four sentences about your professional profile.",
		[TranslationKeys.ProfilePhoto] = "Profile photo",
		[TranslationKeys.ProfilePhotoUploadHint] = "Click to upload a photo",
		[TranslationKeys.ProfilePhotoChangeHint] = "Click to change photo",
		[TranslationKeys.ProfilePhotoUploadButton] = "Upload photo",
		[TranslationKeys.ProfilePhotoRemove] = "Remove photo",
		[TranslationKeys.ProfilePhotoFilePickerTitle] = "Select profile photo",
		[TranslationKeys.ProfilePhotoFileType] = "Images",
		[TranslationKeys.ProfilePhotoUnsupportedFormat] = "Unsupported image format. Use JPEG, PNG, or WebP.",
		[TranslationKeys.ProfilePhotoFileTooLarge] = "Image is too large. Maximum size is 15 MB.",
		[TranslationKeys.ProfilePhotoUnreadable] = "The selected image could not be read.",
		[TranslationKeys.ProfilePhotoMissingOnDisk] = "The profile photo file is missing and was cleared.",
		[TranslationKeys.ExportPdf] = "Export PDF",
		[TranslationKeys.Export] = "Export",
		[TranslationKeys.ExportCv] = "Export CV",
		[TranslationKeys.ExportSaveDialogTitle] = "Export CV",
		[TranslationKeys.ExportSaveDialogTitleFormat] = "Export CV as {0}",
		[TranslationKeys.ExportPdfFileType] = "PDF files",
		[TranslationKeys.ExportDocxFileType] = "Word documents",
		[TranslationKeys.ExportOdtFileType] = "OpenDocument files",
		[TranslationKeys.ExportRtfFileType] = "Rich Text files",
		[TranslationKeys.ExportHtmlFileType] = "HTML files",
		[TranslationKeys.ExportMarkdownFileType] = "Markdown files",
		[TranslationKeys.ExportTxtFileType] = "Plain text files",
		[TranslationKeys.ExportLatexFileType] = "LaTeX files",
		[TranslationKeys.ExportRevitaeJsonFileType] = "ReVitae JSON files",
		[TranslationKeys.ExportJsonResumeFileType] = "JSON Resume files",
		[TranslationKeys.ExportYamlFileType] = "YAML files",
		[TranslationKeys.ExportEuropassXmlFileType] = "Europass XML files",
		[TranslationKeys.ExportHrXmlFileType] = "HR-XML files",
		[TranslationKeys.ExportCsvFileType] = "CSV files",
		[TranslationKeys.ExportTsvFileType] = "TSV files",
		[TranslationKeys.ExportFailed] = "The CV could not be exported. Please try again.",
		[TranslationKeys.ExportFailedFormat] = "The CV could not be exported as {0}. Please try again.",
		[TranslationKeys.ExportModalTitle] = "Export CV",
		[TranslationKeys.ExportModalSubtitle] = "Choose a file format for your download.",
		[TranslationKeys.ExportModalClose] = "Close",
		[TranslationKeys.ExportCategoryDocuments] = "Documents",
		[TranslationKeys.ExportCategoryWebAndText] = "Web & text",
		[TranslationKeys.ExportCategoryStructured] = "Structured data",
		[TranslationKeys.ExportCategoryImages] = "Images",
		[TranslationKeys.ExportFormatPdf] = "PDF",
		[TranslationKeys.ExportFormatPdfHint] = "Best for sharing and printing",
		[TranslationKeys.ExportFormatDocx] = "Word",
		[TranslationKeys.ExportFormatOdt] = "OpenDocument",
		[TranslationKeys.ExportFormatRtf] = "Rich Text",
		[TranslationKeys.ExportFormatHtml] = "HTML",
		[TranslationKeys.ExportFormatMarkdown] = "Markdown",
		[TranslationKeys.ExportFormatTxt] = "Plain text",
		[TranslationKeys.ExportFormatLatex] = "LaTeX",
		[TranslationKeys.ExportFormatRevitaeJson] = "ReVitae JSON",
		[TranslationKeys.ExportFormatJsonResume] = "JSON Resume",
		[TranslationKeys.ExportFormatYaml] = "YAML",
		[TranslationKeys.ExportFormatEuropassXml] = "Europass XML",
		[TranslationKeys.ExportFormatHrXml] = "HR-XML",
		[TranslationKeys.ExportFormatCsv] = "CSV",
		[TranslationKeys.ExportFormatTsv] = "TSV",
		[TranslationKeys.ExportFormatImages] = "Page images",
		[TranslationKeys.ExportFormatImagesHint] = "PNG, JPEG, or WebP — one file per page",
		[TranslationKeys.ExportFormatRecommended] = "Recommended",
		[TranslationKeys.ExportOpenFile] = "Open file",
		[TranslationKeys.ExportShowInFolder] = "Show in folder",
		[TranslationKeys.ExportImageOptionsTitle] = "Image export options",
		[TranslationKeys.ExportImageFormatLabel] = "Image format",
		[TranslationKeys.ExportImageFormatPng] = "PNG (lossless)",
		[TranslationKeys.ExportImageFormatJpeg] = "JPEG (smaller file)",
		[TranslationKeys.ExportImageFormatWebp] = "WebP (modern web)",
		[TranslationKeys.ExportImageDeliveryLabel] = "Delivery",
		[TranslationKeys.ExportImageDeliveryZip] = "Single ZIP archive",
		[TranslationKeys.ExportImageDeliveryZipHint] = "All pages in one .zip file",
		[TranslationKeys.ExportImageDeliverySeparate] = "Separate files",
		[TranslationKeys.ExportImageDeliverySeparateHint] = "Save each page into a folder",
		[TranslationKeys.ExportImageQualityLabel] = "Quality",
		[TranslationKeys.ExportImageScaleLabel] = "Resolution",
		[TranslationKeys.ExportImageScale1x] = "Standard (1×)",
		[TranslationKeys.ExportImageScale2x] = "High (2×)",
		[TranslationKeys.ExportImagePagesLabel] = "Pages",
		[TranslationKeys.ExportImagePagesAll] = "All pages",
		[TranslationKeys.ExportImagePagesRange] = "Page range",
		[TranslationKeys.ExportImagePageFromLabel] = "From",
		[TranslationKeys.ExportImagePageToLabel] = "To",
		[TranslationKeys.ExportImageRangeInvalid] = "Enter a valid page range (From ≤ To, within total pages).",
		[TranslationKeys.ExportImageSizeEstimate] = "{0} pages · ~{1} ({2})",
		[TranslationKeys.ExportImageSizeEstimateUnknown] = "Calculating size…",
		[TranslationKeys.ExportImageProgressRendering] = "Rendering page {0} of {1}…",
		[TranslationKeys.ExportImageProgressWriting] = "Writing files…",
		[TranslationKeys.ExportImageExportButton] = "Export images",
		[TranslationKeys.ExportImageBackButton] = "Back to formats",
		[TranslationKeys.ExportImageOptionsRequired] = "Image export options are missing.",
		[TranslationKeys.ExportImageTooManyPages] = "This CV has too many pages to export as images (max {0}).",
		[TranslationKeys.ExportImageRasterFailed] = "Could not render CV pages as images.",
		[TranslationKeys.ExportZipFileType] = "ZIP archive",
		[TranslationKeys.ExportFolderPickerTitle] = "Choose folder for CV images",
		[TranslationKeys.ExportedImagesToZip] = "Exported {0} page image(s) to {1}.",
		[TranslationKeys.ExportedImagesToFolder] = "Exported {0} page image(s) to folder.",
		[TranslationKeys.ProjectSave] = "Save",
		[TranslationKeys.ProjectSaveAs] = "Save As",
		[TranslationKeys.ProjectOpen] = "Open",
		[TranslationKeys.ProjectSaveDialogTitle] = "Save CV project",
		[TranslationKeys.ProjectOpenDialogTitle] = "Open CV",
		[TranslationKeys.ProjectSaved] = "Saved {0}",
		[TranslationKeys.ProjectOpened] = "Opened {0}",
		[TranslationKeys.ProjectSaveFailed] = "Could not save the project.",
		[TranslationKeys.ProjectOpenFailed] = "Could not open the project.",
		[TranslationKeys.ProjectOpenEmpty] = "The project file contains no CV data.",
		[TranslationKeys.ProjectUntitled] = "Untitled CV",
		[TranslationKeys.ProjectUnsavedIndicator] = "Unsaved changes",
		[TranslationKeys.ProjectUnsavedConfirmTitle] = "Save changes?",
		[TranslationKeys.ProjectUnsavedConfirmMessage] = "Your CV has unsaved changes. Save before continuing?",
		[TranslationKeys.ProjectUnsavedSave] = "Save",
		[TranslationKeys.ProjectUnsavedDiscard] = "Don't save",
		[TranslationKeys.ProjectRecentTitle] = "Recent projects",
		[TranslationKeys.ProjectRecentClear] = "Clear list",
		[TranslationKeys.ProjectRecentClearConfirmTitle] = "Clear recent projects?",
		[TranslationKeys.ProjectRecentClearConfirmMessage] = "This removes the recent projects list. Saved files on disk are not deleted.",
		[TranslationKeys.ProjectRecentMissing] = "File no longer exists",
		[TranslationKeys.ProjectRecoveryTitle] = "Recover unsaved work?",
		[TranslationKeys.ProjectRecoveryMessage] = "ReVitae found an autosaved CV from an unexpected exit.",
		[TranslationKeys.ProjectRecoveryRestore] = "Recover",
		[TranslationKeys.ProjectRecoveryDiscard] = "Discard",
		[TranslationKeys.ProjectSettingsPartiallyIgnored] = "Some editor settings were ignored (newer format).",
		[TranslationKeys.ProjectSavedWithValidationErrors] = "Project saved — fix validation errors before export.",
		[TranslationKeys.ProjectFileType] = "ReVitae project",
		[TranslationKeys.ProjectGenericJsonFileType] = "JSON file",
		[TranslationKeys.Preview] = "Preview",
		[TranslationKeys.PreviewExpandTitle] = "Expanded preview",
		[TranslationKeys.Setup] = "Setup",
		[TranslationKeys.SetupAbout] = "About",
		[TranslationKeys.SetupAppName] = "ReVitae",
		[TranslationKeys.SetupVersion] = "Version",
		[TranslationKeys.SetupEarlyPreview] = "Early preview",
		[TranslationKeys.SetupShowAiWizardAgain] = "Show AI setup wizard again",
		[TranslationKeys.FirstLaunchAiWizardTitle] = "Set up AI (optional)",
		[TranslationKeys.FirstLaunchAiWizardWelcomeLead] = "ReVitae can use AI to help import scanned CVs and suggest improvements to your wording.",
		[TranslationKeys.FirstLaunchAiWizardWelcomeReview] = "You always review suggestions before anything is applied.",
		[TranslationKeys.FirstLaunchAiWizardWelcomePrivacy] = "Local models run on your device. Online providers send text to their servers when you use AI features.",
		[TranslationKeys.FirstLaunchAiWizardWelcomeLanguage] = "Language",
		[TranslationKeys.FirstLaunchAiWizardWelcomeChangeLanguage] = "Change",
		[TranslationKeys.FirstLaunchAiWizardChoosePathTitle] = "How would you like to use AI?",
		[TranslationKeys.FirstLaunchAiWizardPathLocalTitle] = "Free local model",
		[TranslationKeys.FirstLaunchAiWizardPathLocalSubtitle] = "Downloads once; works offline after setup. Recommended if you have enough disk space and RAM.",
		[TranslationKeys.FirstLaunchAiWizardPathOnlineTitle] = "Online provider",
		[TranslationKeys.FirstLaunchAiWizardPathOnlineSubtitle] = "Use your API key (OpenAI, Anthropic, and others).",
		[TranslationKeys.FirstLaunchAiWizardPathSkipTitle] = "Skip for now",
		[TranslationKeys.FirstLaunchAiWizardPathSkipSubtitle] = "Set up AI later — features stay available in the toolbar.",
		[TranslationKeys.FirstLaunchAiWizardPathOfflineTitle] = "I won't use AI",
		[TranslationKeys.FirstLaunchAiWizardPathOfflineSubtitle] = "Build and export your CV without AI suggestions or import assistance.",
		[TranslationKeys.FirstLaunchAiWizardLocalDetecting] = "Analyzing your system…",
		[TranslationKeys.FirstLaunchAiWizardLocalDetectionFailed] = "Could not analyze your system. Try again or skip for now.",
		[TranslationKeys.FirstLaunchAiWizardLocalRecommended] = "Recommended for your system",
		[TranslationKeys.FirstLaunchAiWizardLocalDownloadActivate] = "Download and activate",
		[TranslationKeys.FirstLaunchAiWizardLocalDownloadInProgress] = "Download in progress — you can continue.",
		[TranslationKeys.FirstLaunchAiWizardOnlineMoreProviders] = "More providers…",
		[TranslationKeys.FirstLaunchAiWizardCompleteActiveLocal] = "AI is ready — {0} (local).",
		[TranslationKeys.FirstLaunchAiWizardCompleteActiveOnline] = "AI is ready — {0}.",
		[TranslationKeys.FirstLaunchAiWizardCompleteSkipped] = "No AI configured. You can set it up anytime from the robot icon in the toolbar.",
		[TranslationKeys.FirstLaunchAiWizardCompleteRemindLater] = "No AI configured yet. Set it up anytime from the robot icon or Setup.",
		[TranslationKeys.FirstLaunchAiWizardCompleteOfflineOnly] = "AI features are tucked away. Enable them anytime from Setup or the robot icon.",
		[TranslationKeys.FirstLaunchAiWizardCompleteChangeAiHint] = "You can change AI settings anytime from the robot icon or Setup.",
		[TranslationKeys.FirstLaunchAiWizardSkipConfirm] = "Skip AI setup for now?",
		[TranslationKeys.FirstLaunchAiWizardOfflineConfirm] = "Hide AI features in ReVitae? You can turn them back on later from Setup.",
		[TranslationKeys.FirstLaunchAiWizardSkip] = "Skip for now",
		[TranslationKeys.FirstLaunchAiWizardBack] = "Back",
		[TranslationKeys.FirstLaunchAiWizardNext] = "Next",
		[TranslationKeys.FirstLaunchAiWizardGetStarted] = "Get started",
		[TranslationKeys.FirstLaunchAiWizardStepIndicator] = "Step {0} of {1}",
		[TranslationKeys.FirstLaunchAiWizardRetry] = "Try again",
		[TranslationKeys.Templates] = "Templates",
		[TranslationKeys.Close] = "Close",
		[TranslationKeys.Language] = "Language",
		[TranslationKeys.Selected] = "Selected",
		[TranslationKeys.ClassicSidebar] = "Classic Sidebar",
		[TranslationKeys.ClassicSidebarDescription] = "Light sidebar with contact details and a clean content area.",
		[TranslationKeys.ModernSidebar] = "Modern Sidebar",
		[TranslationKeys.ModernSidebarDescription] = "Compact sidebar with a dark name band and focused content.",
		[TranslationKeys.CleanTopHeader] = "Clean Top Header",
		[TranslationKeys.CleanTopHeaderDescription] = "Safe default with a full-width color header and simple sections.",
		[TranslationKeys.DarkSidebarAccent] = "Dark Sidebar Accent",
		[TranslationKeys.DarkSidebarAccentDescription] = "Dark sidebar, colored header, and stronger visual personality.",
		[TranslationKeys.CenteredMinimal] = "Centered Minimal",
		[TranslationKeys.CenteredMinimalDescription] = "Single-column layout with centered name, boxed summary, and dark contact bar.",
		[TranslationKeys.PhotoLeftBand] = "Photo Left Band",
		[TranslationKeys.PhotoLeftBandDescription] = "Portrait on the left, name on the right, and a full-width summary band.",
		[TranslationKeys.ExecutiveBlueSidebar] = "Executive Blue Sidebar",
		[TranslationKeys.ExecutiveBlueSidebarDescription] = "Gray sidebar with navy accents, circular photo, and structured main column.",
		[TranslationKeys.PeachDesigner] = "Peach Designer",
		[TranslationKeys.PeachDesignerDescription] = "Peach header contact card, rounded gray sidebar, and warm accent bars.",
		[TranslationKeys.NavyProfileSplit] = "Navy Profile Split",
		[TranslationKeys.NavyProfileSplitDescription] = "Navy header with orange section titles and a two-column experience layout.",
		[TranslationKeys.ForestGreenSidebar] = "Forest Green Sidebar",
		[TranslationKeys.ForestGreenSidebarDescription] = "Forest-green name blocks, rectangular photo, and sidebar contact details.",
		[TranslationKeys.YellowSkillDots] = "Yellow Skill Dots",
		[TranslationKeys.YellowSkillDotsDescription] = "Yellow accent squares, right-column photo, and dotted skill proficiency rows.",
		[TranslationKeys.RoyalBlueSidebar] = "Royal Blue Sidebar",
		[TranslationKeys.RoyalBlueSidebarDescription] = "Full-height royal-blue sidebar with a dark header band and circular photo.",
		[TranslationKeys.OrangeTimeline] = "Orange Timeline",
		[TranslationKeys.OrangeTimelineDescription] = "Single-column résumé with an orange vertical timeline and circular photo header.",
		[TranslationKeys.BlueAccentSummary] = "Blue Accent Summary",
		[TranslationKeys.BlueAccentSummaryDescription] = "Blue accent bar, bordered summary box, and photo aligned to the header.",
		[TranslationKeys.PillHeaderSplit] = "Pill Header Split",
		[TranslationKeys.PillHeaderSplitDescription] = "Circular photo with a rounded contact pill and a two-column skills layout.",
		[TranslationKeys.NavyOverlapPhoto] = "Navy Overlap Photo",
		[TranslationKeys.NavyOverlapPhotoDescription] = "Navy header band with an overlapping circular photo and split columns below.",
		[TranslationKeys.Summary] = "Summary",
		[TranslationKeys.Contact] = "Contact",
		[TranslationKeys.ContactLinks] = "Contact Links",
		[TranslationKeys.Profile] = "Profile",
		[TranslationKeys.Digital] = "Digital",
		[TranslationKeys.Links] = "Links",
		[TranslationKeys.Objective] = "Objective",
		[TranslationKeys.Online] = "Online",
		[TranslationKeys.ExportFixValidation] = "Fix validation errors before exporting.",
		[TranslationKeys.ExportFilePickerUnavailable] = "Unable to open the file picker.",
		[TranslationKeys.ExportedPdfTo] = "Exported PDF to {0}.",
		[TranslationKeys.ExportedTo] = "Exported to {0}.",
		[TranslationKeys.ValidationFirstNameRequired] = "First name is required.",
		[TranslationKeys.ValidationLastNameRequired] = "Last name is required.",
		[TranslationKeys.ValidationEmailRequired] = "Email is required.",
		[TranslationKeys.ValidationFirstNameMax] = "First name must be 80 characters or fewer.",
		[TranslationKeys.ValidationLastNameMax] = "Last name must be 80 characters or fewer.",
		[TranslationKeys.ValidationProfessionalTitleMax] = "Professional title must be 120 characters or fewer.",
		[TranslationKeys.ValidationEmailMax] = "Email must be 160 characters or fewer.",
		[TranslationKeys.ValidationPhoneMax] = "Phone must be 40 characters or fewer.",
		[TranslationKeys.ValidationLocationMax] = "Location must be 120 characters or fewer.",
		[TranslationKeys.ValidationLinkedInUrlMax] = "LinkedIn URL must be 240 characters or fewer.",
		[TranslationKeys.ValidationPortfolioUrlMax] = "Portfolio / website URL must be 240 characters or fewer.",
		[TranslationKeys.ValidationGitHubUrlMax] = "GitHub URL must be 240 characters or fewer.",
		[TranslationKeys.ValidationShortSummaryMax] = "Short summary must be 800 characters or fewer.",
		[TranslationKeys.ValidationEmailFormat] = "Email must be a valid email address.",
		[TranslationKeys.ValidationLinkedInUrlFormat] = "LinkedIn URL must be a valid http or https URL.",
		[TranslationKeys.ValidationPortfolioUrlFormat] = "Portfolio / website URL must be a valid http or https URL.",
		[TranslationKeys.ValidationGitHubUrlFormat] = "GitHub URL must be a valid http or https URL.",
		[TranslationKeys.WorkExperience] = "Work Experience",
		[TranslationKeys.WorkExperienceEmptyHint] = "Add your most recent role first. You can reorder entries later.",
		[TranslationKeys.WorkExperienceAdd] = "Add experience",
		[TranslationKeys.WorkExperienceDuplicate] = "Duplicate",
		[TranslationKeys.WorkExperienceRemove] = "Remove",
		[TranslationKeys.WorkExperienceSortByDate] = "Sort by date (newest first)",
		[TranslationKeys.WorkExperienceJobTitle] = "Job title",
		[TranslationKeys.WorkExperienceCompany] = "Company",
		[TranslationKeys.WorkExperienceLocation] = "Location",
		[TranslationKeys.WorkExperienceEmploymentType] = "Employment type",
		[TranslationKeys.WorkExperienceStartDate] = "Start date",
		[TranslationKeys.WorkExperienceEndDate] = "End date",
		[TranslationKeys.WorkExperienceStartMonth] = "Start month",
		[TranslationKeys.WorkExperienceStartYear] = "Start year",
		[TranslationKeys.WorkExperienceEndMonth] = "End month",
		[TranslationKeys.WorkExperienceEndYear] = "End year",
		[TranslationKeys.WorkExperienceCurrentlyWorking] = "Currently working here",
		[TranslationKeys.WorkExperienceDescription] = "Description",
		[TranslationKeys.WorkExperienceAchievements] = "Achievements",
		[TranslationKeys.WorkExperienceTechnologies] = "Technologies",
		[TranslationKeys.WorkExperienceCompanyUrl] = "Company URL",
		[TranslationKeys.WorkExperiencePresent] = "Present",
		[TranslationKeys.WorkExperienceDragToReorder] = "Drag to reorder",
		[TranslationKeys.WorkExperienceExpand] = "Expand entry",
		[TranslationKeys.WorkExperienceCollapse] = "Collapse entry",
		[TranslationKeys.WorkExperienceValidationErrors] = "{0} errors",
		[TranslationKeys.EmploymentTypeFullTime] = "Full-time",
		[TranslationKeys.EmploymentTypePartTime] = "Part-time",
		[TranslationKeys.EmploymentTypeContract] = "Contract",
		[TranslationKeys.EmploymentTypeFreelance] = "Freelance",
		[TranslationKeys.EmploymentTypeInternship] = "Internship",
		[TranslationKeys.PreviewWorkExperience] = "Work Experience",
		[TranslationKeys.PreviewAchievements] = "Achievements",
		[TranslationKeys.PreviewTechnologies] = "Technologies",
		[TranslationKeys.ExpandSection] = "Expand section",
		[TranslationKeys.CollapseSection] = "Collapse section",
		[TranslationKeys.ValidationWorkExperienceJobTitleRequired] = "Job title is required.",
		[TranslationKeys.ValidationWorkExperienceJobTitleMax] = "Job title must be 120 characters or fewer.",
		[TranslationKeys.ValidationWorkExperienceCompanyRequired] = "Company is required.",
		[TranslationKeys.ValidationWorkExperienceCompanyMax] = "Company must be 160 characters or fewer.",
		[TranslationKeys.ValidationWorkExperienceLocationMax] = "Location must be 120 characters or fewer.",
		[TranslationKeys.ValidationWorkExperienceEmploymentTypeRequired] = "Employment type is required.",
		[TranslationKeys.ValidationWorkExperienceEmploymentTypeInvalid] = "Employment type must be a supported value.",
		[TranslationKeys.ValidationWorkExperienceStartMonthRequired] = "Start month is required.",
		[TranslationKeys.ValidationWorkExperienceStartMonthInvalid] = "Start month must be between 1 and 12.",
		[TranslationKeys.ValidationWorkExperienceStartYearRequired] = "Start year is required.",
		[TranslationKeys.ValidationWorkExperienceStartYearInvalid] = "Start year must be between 1950 and 2100.",
		[TranslationKeys.ValidationWorkExperienceEndMonthRequired] = "End month is required.",
		[TranslationKeys.ValidationWorkExperienceEndMonthInvalid] = "End month must be between 1 and 12.",
		[TranslationKeys.ValidationWorkExperienceEndYearRequired] = "End year is required.",
		[TranslationKeys.ValidationWorkExperienceEndYearInvalid] = "End year must be between 1950 and 2100.",
		[TranslationKeys.ValidationWorkExperienceDescriptionMax] = "Description must be 2000 characters or fewer.",
		[TranslationKeys.ValidationWorkExperienceAchievementsMax] = "Achievements must be 2000 characters or fewer.",
		[TranslationKeys.ValidationWorkExperienceTechnologiesMax] = "Technologies must be 500 characters or fewer.",
		[TranslationKeys.ValidationWorkExperienceCompanyUrlMax] = "Company URL must be 240 characters or fewer.",
		[TranslationKeys.ValidationWorkExperienceCompanyUrlFormat] = "Company URL must be a valid http or https URL.",
		[TranslationKeys.ValidationWorkExperienceStartAfterEnd] = "Start date must not be after end date.",
		[TranslationKeys.Education] = "Education",
		[TranslationKeys.EducationEmptyHint] = "Add your most recent qualification first. You can reorder entries later.",
		[TranslationKeys.EducationAdd] = "Add education",
		[TranslationKeys.EducationDuplicate] = "Duplicate",
		[TranslationKeys.EducationRemove] = "Remove",
		[TranslationKeys.EducationSortByDate] = "Sort by date (newest first)",
		[TranslationKeys.EducationInstitution] = "Institution",
		[TranslationKeys.EducationDegree] = "Degree",
		[TranslationKeys.EducationFieldOfStudy] = "Field of study",
		[TranslationKeys.EducationLocation] = "Location",
		[TranslationKeys.EducationDegreeType] = "Degree type",
		[TranslationKeys.EducationStartDate] = "Start date",
		[TranslationKeys.EducationEndDate] = "End date",
		[TranslationKeys.EducationStartMonth] = "Start month",
		[TranslationKeys.EducationStartYear] = "Start year",
		[TranslationKeys.EducationEndMonth] = "End month",
		[TranslationKeys.EducationEndYear] = "End year",
		[TranslationKeys.EducationCurrentlyStudying] = "Currently studying here",
		[TranslationKeys.EducationGrade] = "Grade",
		[TranslationKeys.EducationDescription] = "Description",
		[TranslationKeys.EducationInstitutionUrl] = "Institution URL",
		[TranslationKeys.EducationPresent] = "Present",
		[TranslationKeys.EducationDragToReorder] = "Drag to reorder",
		[TranslationKeys.EducationExpand] = "Expand entry",
		[TranslationKeys.EducationCollapse] = "Collapse entry",
		[TranslationKeys.EducationValidationErrors] = "{0} errors",
		[TranslationKeys.DegreeTypeHighSchool] = "High school",
		[TranslationKeys.DegreeTypeAssociate] = "Associate",
		[TranslationKeys.DegreeTypeBachelor] = "Bachelor",
		[TranslationKeys.DegreeTypeMaster] = "Master",
		[TranslationKeys.DegreeTypeDoctorate] = "Doctorate",
		[TranslationKeys.DegreeTypeCertificate] = "Certificate",
		[TranslationKeys.DegreeTypeOther] = "Other",
		[TranslationKeys.PreviewEducation] = "Education",
		[TranslationKeys.PreviewGrade] = "Grade",
		[TranslationKeys.PreviewFieldOfStudy] = "Field of study",
		[TranslationKeys.ValidationEducationInstitutionRequired] = "Institution is required.",
		[TranslationKeys.ValidationEducationInstitutionMax] = "Institution must be 160 characters or fewer.",
		[TranslationKeys.ValidationEducationDegreeRequired] = "Degree is required.",
		[TranslationKeys.ValidationEducationDegreeMax] = "Degree must be 160 characters or fewer.",
		[TranslationKeys.ValidationEducationFieldOfStudyMax] = "Field of study must be 160 characters or fewer.",
		[TranslationKeys.ValidationEducationLocationMax] = "Location must be 120 characters or fewer.",
		[TranslationKeys.ValidationEducationDegreeTypeRequired] = "Degree type is required.",
		[TranslationKeys.ValidationEducationDegreeTypeInvalid] = "Degree type must be a supported value.",
		[TranslationKeys.ValidationEducationStartMonthRequired] = "Start month is required.",
		[TranslationKeys.ValidationEducationStartMonthInvalid] = "Start month must be between 1 and 12.",
		[TranslationKeys.ValidationEducationStartYearRequired] = "Start year is required.",
		[TranslationKeys.ValidationEducationStartYearInvalid] = "Start year must be between 1950 and 2100.",
		[TranslationKeys.ValidationEducationEndMonthRequired] = "End month is required.",
		[TranslationKeys.ValidationEducationEndMonthInvalid] = "End month must be between 1 and 12.",
		[TranslationKeys.ValidationEducationEndYearRequired] = "End year is required.",
		[TranslationKeys.ValidationEducationEndYearInvalid] = "End year must be between 1950 and 2100.",
		[TranslationKeys.ValidationEducationGradeMax] = "Grade must be 80 characters or fewer.",
		[TranslationKeys.ValidationEducationDescriptionMax] = "Description must be 2000 characters or fewer.",
		[TranslationKeys.ValidationEducationInstitutionUrlMax] = "Institution URL must be 240 characters or fewer.",
		[TranslationKeys.ValidationEducationInstitutionUrlFormat] = "Institution URL must be a valid http or https URL.",
		[TranslationKeys.ValidationEducationStartAfterEnd] = "Start date must not be after end date.",
		[TranslationKeys.Skills] = "Skills",
		[TranslationKeys.SkillsEmptyHint] = "Group related skills together. You can reorder groups later.",
		[TranslationKeys.SkillsAdd] = "Add skill group",
		[TranslationKeys.SkillsDuplicate] = "Duplicate",
		[TranslationKeys.SkillsRemove] = "Remove",
		[TranslationKeys.SkillsCategory] = "Category",
		[TranslationKeys.SkillsSkillName] = "Skill",
		[TranslationKeys.SkillsProficiency] = "Proficiency",
		[TranslationKeys.SkillsYearsOfExperience] = "Years",
		[TranslationKeys.SkillsAddSkill] = "Add skill",
		[TranslationKeys.SkillsAddFromList] = "Add from list",
		[TranslationKeys.SkillsBulkSkills] = "Bulk add skills",
		[TranslationKeys.SkillsBulkSkillsPlaceholder] = "C#, TypeScript, Git or one skill per line",
		[TranslationKeys.SkillsRemoveSkill] = "Remove skill",
		[TranslationKeys.SkillsDragToReorder] = "Drag to reorder",
		[TranslationKeys.SkillsDragSkillToMove] = "Drag skill to move between groups",
		[TranslationKeys.SkillsExpand] = "Expand entry",
		[TranslationKeys.SkillsCollapse] = "Collapse entry",
		[TranslationKeys.SkillsValidationErrors] = "{0} errors",
		[TranslationKeys.ProficiencyBeginner] = "Beginner",
		[TranslationKeys.ProficiencyIntermediate] = "Intermediate",
		[TranslationKeys.ProficiencyAdvanced] = "Advanced",
		[TranslationKeys.ProficiencyExpert] = "Expert",
		[TranslationKeys.PreviewSkills] = "Skills",
		[TranslationKeys.PreviewYearsSuffix] = "yrs",
		[TranslationKeys.ValidationSkillsCategoryRequired] = "Category is required.",
		[TranslationKeys.ValidationSkillsCategoryMax] = "Category must be 120 characters or fewer.",
		[TranslationKeys.ValidationSkillsSkillNameRequired] = "Skill name is required.",
		[TranslationKeys.ValidationSkillsSkillNameMax] = "Skill name must be 80 characters or fewer.",
		[TranslationKeys.ValidationSkillsAtLeastOneRequired] = "Add at least one skill to this group.",
		[TranslationKeys.ValidationSkillsProficiencyRequired] = "Proficiency is required.",
		[TranslationKeys.ValidationSkillsProficiencyInvalid] = "Proficiency must be a supported value.",
		[TranslationKeys.ValidationSkillsYearsOfExperienceInvalid] = "Years of experience must be between 0 and 60.",
		[TranslationKeys.ValidationSkillsDuplicateInGroup] = "This skill is already listed in this group.",
		[TranslationKeys.ValidationSkillsBulkSkillsMax] = "Bulk skills text must be 1000 characters or fewer.",
		[TranslationKeys.Languages] = "Languages",
		[TranslationKeys.LanguagesEmptyHint] = "Add your strongest languages first. You can reorder entries later.",
		[TranslationKeys.LanguagesAdd] = "Add language",
		[TranslationKeys.LanguagesDuplicate] = "Duplicate",
		[TranslationKeys.LanguagesRemove] = "Remove",
		[TranslationKeys.LanguagesLanguage] = "Language",
		[TranslationKeys.LanguagesProficiency] = "Proficiency",
		[TranslationKeys.LanguagesCefrLevel] = "CEFR level",
		[TranslationKeys.LanguagesCertificate] = "Certificate or note",
		[TranslationKeys.LanguagesReading] = "Reading",
		[TranslationKeys.LanguagesWriting] = "Writing",
		[TranslationKeys.LanguagesSpeaking] = "Speaking",
		[TranslationKeys.LanguagesListening] = "Listening",
		[TranslationKeys.LanguagesSubSkills] = "Sub-skills",
		[TranslationKeys.LanguagesCefrNone] = "Not specified",
		[TranslationKeys.LanguagesProficiencyNone] = "Not specified",
		[TranslationKeys.LanguagesDragToReorder] = "Drag to reorder",
		[TranslationKeys.LanguagesExpand] = "Expand entry",
		[TranslationKeys.LanguagesCollapse] = "Collapse entry",
		[TranslationKeys.LanguagesValidationErrors] = "{0} errors",
		[TranslationKeys.LanguageProficiencyElementary] = "Elementary",
		[TranslationKeys.LanguageProficiencyIntermediate] = "Intermediate",
		[TranslationKeys.LanguageProficiencyAdvanced] = "Advanced",
		[TranslationKeys.LanguageProficiencyFluent] = "Fluent",
		[TranslationKeys.LanguageProficiencyNative] = "Native",
		[TranslationKeys.CefrA1] = "A1",
		[TranslationKeys.CefrA2] = "A2",
		[TranslationKeys.CefrB1] = "B1",
		[TranslationKeys.CefrB2] = "B2",
		[TranslationKeys.CefrC1] = "C1",
		[TranslationKeys.CefrC2] = "C2",
		[TranslationKeys.PreviewLanguages] = "Languages",
		[TranslationKeys.PreviewReading] = "Reading",
		[TranslationKeys.PreviewWriting] = "Writing",
		[TranslationKeys.PreviewSpeaking] = "Speaking",
		[TranslationKeys.PreviewListening] = "Listening",
		[TranslationKeys.ValidationLanguagesLanguageRequired] = "Language is required.",
		[TranslationKeys.ValidationLanguagesLanguageMax] = "Language must be 80 characters or fewer.",
		[TranslationKeys.ValidationLanguagesProficiencyRequired] = "Proficiency is required.",
		[TranslationKeys.ValidationLanguagesProficiencyInvalid] = "Proficiency must be a supported value.",
		[TranslationKeys.ValidationLanguagesCefrInvalid] = "CEFR level must be a supported value.",
		[TranslationKeys.ValidationLanguagesCertificateMax] = "Certificate or note must be 120 characters or fewer.",
		[TranslationKeys.ValidationLanguagesDuplicateLanguage] = "This language is already listed.",
		[TranslationKeys.Certificates] = "Certificates",
		[TranslationKeys.CertificatesEmptyHint] = "Add your most relevant certifications first. You can reorder entries later.",
		[TranslationKeys.CertificatesAdd] = "Add certificate",
		[TranslationKeys.CertificatesDuplicate] = "Duplicate",
		[TranslationKeys.CertificatesRemove] = "Remove",
		[TranslationKeys.CertificatesSortByDate] = "Sort by date (newest first)",
		[TranslationKeys.CertificatesName] = "Certificate name",
		[TranslationKeys.CertificatesIssuer] = "Issuing organization",
		[TranslationKeys.CertificatesIssueDate] = "Issue date",
		[TranslationKeys.CertificatesExpirationDate] = "Expiration date",
		[TranslationKeys.CertificatesIssueMonth] = "Issue month",
		[TranslationKeys.CertificatesIssueYear] = "Issue year",
		[TranslationKeys.CertificatesExpirationMonth] = "Expiration month",
		[TranslationKeys.CertificatesExpirationYear] = "Expiration year",
		[TranslationKeys.CertificatesCredentialId] = "Credential ID",
		[TranslationKeys.CertificatesCredentialUrl] = "Credential URL",
		[TranslationKeys.CertificatesDescription] = "Description or note",
		[TranslationKeys.CertificatesDragToReorder] = "Drag to reorder",
		[TranslationKeys.CertificatesExpand] = "Expand entry",
		[TranslationKeys.CertificatesCollapse] = "Collapse entry",
		[TranslationKeys.CertificatesValidationErrors] = "{0} errors",
		[TranslationKeys.PreviewCertificates] = "Certificates",
		[TranslationKeys.PreviewValidUntil] = "Valid until",
		[TranslationKeys.PreviewCredentialId] = "Credential ID",
		[TranslationKeys.PreviewCredentialUrl] = "Credential URL",
		[TranslationKeys.ValidationCertificatesNameRequired] = "Certificate name is required.",
		[TranslationKeys.ValidationCertificatesNameMax] = "Certificate name must be 160 characters or fewer.",
		[TranslationKeys.ValidationCertificatesIssuerRequired] = "Issuing organization is required.",
		[TranslationKeys.ValidationCertificatesIssuerMax] = "Issuing organization must be 160 characters or fewer.",
		[TranslationKeys.ValidationCertificatesIssueMonthRequired] = "Issue month is required.",
		[TranslationKeys.ValidationCertificatesIssueMonthInvalid] = "Issue month must be between 1 and 12.",
		[TranslationKeys.ValidationCertificatesIssueYearRequired] = "Issue year is required.",
		[TranslationKeys.ValidationCertificatesIssueYearInvalid] = "Issue year must be between 1950 and 2100.",
		[TranslationKeys.ValidationCertificatesExpirationMonthInvalid] = "Expiration month must be between 1 and 12.",
		[TranslationKeys.ValidationCertificatesExpirationYearInvalid] = "Expiration year must be between 1950 and 2100.",
		[TranslationKeys.ValidationCertificatesCredentialIdMax] = "Credential ID must be 80 characters or fewer.",
		[TranslationKeys.ValidationCertificatesCredentialUrlMax] = "Credential URL must be 240 characters or fewer.",
		[TranslationKeys.ValidationCertificatesCredentialUrlFormat] = "Credential URL must be a valid http or https URL.",
		[TranslationKeys.ValidationCertificatesDescriptionMax] = "Description or note must be 500 characters or fewer.",
		[TranslationKeys.ValidationCertificatesIssueAfterExpiration] = "Issue date must not be after expiration date.",
		[TranslationKeys.Projects] = "Projects",
		[TranslationKeys.ProjectsEmptyHint] = "Add your strongest projects first. You can reorder entries later.",
		[TranslationKeys.ProjectsAdd] = "Add project",
		[TranslationKeys.ProjectsDuplicate] = "Duplicate",
		[TranslationKeys.ProjectsRemove] = "Remove",
		[TranslationKeys.ProjectsSortByDate] = "Sort by date (newest first)",
		[TranslationKeys.ProjectsName] = "Project name",
		[TranslationKeys.ProjectsRole] = "Role",
		[TranslationKeys.ProjectsOrganization] = "Organization or context",
		[TranslationKeys.ProjectsStartDate] = "Start date",
		[TranslationKeys.ProjectsEndDate] = "End date",
		[TranslationKeys.ProjectsStartMonth] = "Start month",
		[TranslationKeys.ProjectsStartYear] = "Start year",
		[TranslationKeys.ProjectsEndMonth] = "End month",
		[TranslationKeys.ProjectsEndYear] = "End year",
		[TranslationKeys.ProjectsCurrentlyActive] = "Currently active",
		[TranslationKeys.ProjectsProjectUrl] = "Project URL",
		[TranslationKeys.ProjectsTechnologyName] = "Technology",
		[TranslationKeys.ProjectsAddTechnology] = "Add technology",
		[TranslationKeys.ProjectsBulkTechnologies] = "Bulk technologies",
		[TranslationKeys.ProjectsBulkTechnologiesPlaceholder] = "Enter technologies separated by commas or new lines",
		[TranslationKeys.ProjectsAddFromList] = "Add from list",
		[TranslationKeys.ProjectsRemoveTechnology] = "Remove technology",
		[TranslationKeys.ProjectsHighlights] = "Highlights",
		[TranslationKeys.ProjectsDescription] = "Description",
		[TranslationKeys.ProjectsDragToReorder] = "Drag to reorder",
		[TranslationKeys.ProjectsExpand] = "Expand entry",
		[TranslationKeys.ProjectsCollapse] = "Collapse entry",
		[TranslationKeys.ProjectsValidationErrors] = "{0} errors",
		[TranslationKeys.ProjectsPresent] = "Present",
		[TranslationKeys.PreviewProjects] = "Projects",
		[TranslationKeys.PreviewHighlights] = "Highlights",
		[TranslationKeys.ValidationProjectsNameRequired] = "Project name is required.",
		[TranslationKeys.ValidationProjectsNameMax] = "Project name must be 160 characters or fewer.",
		[TranslationKeys.ValidationProjectsRoleMax] = "Role must be 120 characters or fewer.",
		[TranslationKeys.ValidationProjectsOrganizationMax] = "Organization or context must be 160 characters or fewer.",
		[TranslationKeys.ValidationProjectsStartMonthInvalid] = "Start month must be between 1 and 12.",
		[TranslationKeys.ValidationProjectsStartYearInvalid] = "Start year must be between 1950 and 2100.",
		[TranslationKeys.ValidationProjectsEndMonthInvalid] = "End month must be between 1 and 12.",
		[TranslationKeys.ValidationProjectsEndYearInvalid] = "End year must be between 1950 and 2100.",
		[TranslationKeys.ValidationProjectsProjectUrlMax] = "Project URL must be 240 characters or fewer.",
		[TranslationKeys.ValidationProjectsProjectUrlFormat] = "Project URL must be a valid http or https URL.",
		[TranslationKeys.ValidationProjectsHighlightsMax] = "Highlights must be 2000 characters or fewer.",
		[TranslationKeys.ValidationProjectsDescriptionMax] = "Description must be 2000 characters or fewer.",
		[TranslationKeys.ValidationProjectsTechnologyNameRequired] = "Technology name is required.",
		[TranslationKeys.ValidationProjectsTechnologyNameMax] = "Technology name must be 80 characters or fewer.",
		[TranslationKeys.ValidationProjectsDuplicateTechnology] = "This technology is already listed in this project.",
		[TranslationKeys.ValidationProjectsBulkTechnologiesMax] = "Bulk technologies text must be 1000 characters or fewer.",
		[TranslationKeys.ValidationProjectsStartAfterEnd] = "Start date must not be after end date.",
		[TranslationKeys.CustomLinks] = "Links",
		[TranslationKeys.CustomLinksEmptyHint] = "Add links to profiles, portfolios, or publications that are not already in your main contact details.",
		[TranslationKeys.CustomLinksAdd] = "Add link",
		[TranslationKeys.CustomLinksDuplicate] = "Duplicate",
		[TranslationKeys.CustomLinksRemove] = "Remove",
		[TranslationKeys.CustomLinksLabel] = "Label",
		[TranslationKeys.CustomLinksUrl] = "URL",
		[TranslationKeys.CustomLinksNote] = "Note",
		[TranslationKeys.CustomLinksDragToReorder] = "Drag to reorder",
		[TranslationKeys.CustomLinksExpand] = "Expand entry",
		[TranslationKeys.CustomLinksCollapse] = "Collapse entry",
		[TranslationKeys.CustomLinksValidationErrors] = "{0} errors",
		[TranslationKeys.PreviewCustomLinks] = "Links",
		[TranslationKeys.ValidationLinksLabelRequired] = "Label is required.",
		[TranslationKeys.ValidationLinksLabelMax] = "Label must be 80 characters or fewer.",
		[TranslationKeys.ValidationLinksUrlRequired] = "URL is required.",
		[TranslationKeys.ValidationLinksUrlMax] = "URL must be 240 characters or fewer.",
		[TranslationKeys.ValidationLinksUrlFormat] = "URL must be a valid http or https URL.",
		[TranslationKeys.ValidationLinksNoteMax] = "Note must be 120 characters or fewer.",
		[TranslationKeys.ValidationLinksDuplicateUrl] = "This URL is already listed.",
		[TranslationKeys.AdditionalInformation] = "Additional Information",
		[TranslationKeys.AdditionalInformationEmptyHint] = "Use this section for interests, volunteering, publications, or other notes that do not belong elsewhere.",
		[TranslationKeys.AdditionalInformationContent] = "Content",
		[TranslationKeys.AdditionalInformationValidationErrors] = "{0} errors",
		[TranslationKeys.PreviewAdditionalInformation] = "Additional Information",
		[TranslationKeys.ValidationAdditionalInformationContentMax] = "Content must be 3000 characters or fewer.",
		[TranslationKeys.IntroTitle] = "Welcome to ReVitae",
		[TranslationKeys.IntroSubtitle] = "Create a new CV from scratch or import an existing file to get started faster.",
		[TranslationKeys.IntroHelper] =
			"Works with PDF, Word, OpenDocument, RTF, text, Markdown, HTML, JSON, XML, JPEG/PNG images, and other common CV files. "
			+ "Scanned or image-only PDFs and photos can be imported using built-in OCR when available.",
		[TranslationKeys.IntroCreateNew] = "Create new CV",
		[TranslationKeys.IntroOpenProject] = "Open saved project",
		[TranslationKeys.IntroImportPdf] = "Import existing CV",
		[TranslationKeys.IntroReadingPdf] = "Reading document…",
		[TranslationKeys.IntroParsingCv] = "Parsing CV…",
		[TranslationKeys.IntroImportRetry] = "Try import again",
		[TranslationKeys.ReplaceCvConfirmTitle] = "Replace current CV?",
		[TranslationKeys.ReplaceCvConfirmMessage] =
			"Importing a new file will replace all current CV data. Do you want to continue?",
		[TranslationKeys.NewCvConfirmTitle] = "Discard changes?",
		[TranslationKeys.NewCvConfirmMessage] =
			"Creating a new CV will discard all current data. Do you want to continue?",
		[TranslationKeys.UploadCvFilePickerTitle] = "Upload CV",
		[TranslationKeys.ImportCvFilePickerTitle] = "Import CV",
		[TranslationKeys.ImportPdfFileType] = "Supported CV files",
		[TranslationKeys.ImportPdfOnlyFileType] = "PDF documents",
		[TranslationKeys.ImportPlainTextFileType] = "Plain text",
		[TranslationKeys.ImportErrorFileNotFound] = "The selected file could not be found.",
		[TranslationKeys.ImportErrorEmptyPdf] = "This PDF does not contain extractable text.",
		[TranslationKeys.ImportErrorUnreadablePdf] = "The PDF could not be read.",
		[TranslationKeys.ImportErrorPasswordProtected] = "Password-protected documents are not supported.",
		[TranslationKeys.ImportErrorNoStructuredData] = "No usable CV content could be extracted.",
		[TranslationKeys.ImportWarningNoSectionsDetected] = "No CV sections were detected. Content was placed into Additional Information.",
		[TranslationKeys.ImportWarningNameUncertain] = "The candidate name could not be parsed confidently.",
		[TranslationKeys.ImportWarningWorkExperiencePartial] = "Some work experience entries may be incomplete.",
		[TranslationKeys.ImportWarningUnmappedTextAppended] = "Some text could not be mapped and was appended to Additional Information.",
		[TranslationKeys.ImportWarningPersonalLinksDuplicatedSkipped] = "A URL already stored in personal information was skipped in Links.",
		[TranslationKeys.ImportDefaultSkillsCategory] = "General",
		[TranslationKeys.ImportErrorEmptyDocument] = "The file does not contain extractable text.",
		[TranslationKeys.ImportErrorUnreadableDocument] = "The file could not be read.",
		[TranslationKeys.ImportErrorUnsupportedFormat] =
			"This file type is not supported. Export the CV as PDF, DOCX, RTF, or plain text and try again.",
		[TranslationKeys.ImportErrorUnsupportedStructuredFormat] = "The file is recognized, but its structure is not supported.",
		[TranslationKeys.ImportErrorFileTooLarge] = "This file is too large to import. Maximum size is 25 MB.",
		[TranslationKeys.ImportWarningPartialDocumentContent] = "Some document content could not be imported.",
		[TranslationKeys.ImportWarningLatexPartiallyNormalized] = "LaTeX markup was simplified before parsing.",
		[TranslationKeys.ImportWarningTabularMultipleRowsIgnored] = "Only the first row of the table was imported.",
		[TranslationKeys.ImportRunningOcr] = "Recognizing text from image…",
		[TranslationKeys.ImportWarningOcrUsed] = "This file was read using OCR. Please review all fields carefully.",
		[TranslationKeys.ImportErrorOcrUnavailable] = "OCR is not available on this system.",
		[TranslationKeys.ImportErrorOcrFailed] = "Could not recognize text in this image or scan.",
		[TranslationKeys.ImportRasterImageFileType] = "Images (JPEG, PNG, …)",
		[TranslationKeys.ImportForceOcr] = "Import as scan (OCR)",
		[TranslationKeys.ImportAiTryButton] = "Try AI import",
		[TranslationKeys.IntroImportTryAi] = "Try AI import",
		[TranslationKeys.ReplaceImportTryAi] = "Try AI import",
		[TranslationKeys.ImportAiEnhanceButton] = "Enhance with AI",
		[TranslationKeys.ImportAiProgressTitle] = "AI import",
		[TranslationKeys.ImportAiProgressStep] = "Step {0} of {1} — {2}",
		[TranslationKeys.ImportAiProgressBatch] = "(batch {0} of {1})",
		[TranslationKeys.ImportAiReviewTitle] = "Review AI import",
		[TranslationKeys.ImportAiReviewSummaryTitle] = "Section summary",
		[TranslationKeys.ImportAiReviewSummaryBefore] = "Before",
		[TranslationKeys.ImportAiReviewSummaryAfter] = "After (AI)",
		[TranslationKeys.ImportAiReviewSectionsImproved] = "Sections improved: {0}",
		[TranslationKeys.ImportAiReviewPersonalPartial] = "partial",
		[TranslationKeys.ImportAiReviewPersonalComplete] = "complete",
		[TranslationKeys.ImportAiReviewEmptyDash] = "—",
		[TranslationKeys.ImportAiReviewEntryCount] = "{0} entries",
		[TranslationKeys.ImportAiPhotoNotExtracted] = "AI import fills text fields only. Add a profile photo manually.",
		[TranslationKeys.ImportAiReviewDetails] = "Details",
		[TranslationKeys.ImportAiReviewWarning] = "AI-generated content — review all fields before export.",
		[TranslationKeys.ImportAiReviewApply] = "Apply to form",
		[TranslationKeys.ImportAiReviewCancel] = "Cancel",
		[TranslationKeys.ImportAiReviewMergeEmpty] = "Fill empty fields only",
		[TranslationKeys.ImportAiOnlineConfirm] = "CV text will be sent to {0} in multiple steps. Continue?",
		[TranslationKeys.ImportAiFailed] = "AI import could not extract usable CV data.",
		[TranslationKeys.ImportAiPartialWarning] = "Some steps failed — review incomplete sections carefully.",
		[TranslationKeys.ImportAiNoBackend] = "Set up AI to use AI import.",
		[TranslationKeys.ImportAiBannerIncomplete] = "Import may be incomplete.",
		[TranslationKeys.ImportWarningAiAssisted] = "This draft was created with AI assistance — verify all fields.",
		[TranslationKeys.ImportWarningAiPartial] = "AI import skipped some sections due to errors.",
		[TranslationKeys.ImportAiPhasePersonal] = "Personal information",
		[TranslationKeys.ImportAiPhaseWork] = "Work experience",
		[TranslationKeys.ImportAiPhaseEducation] = "Education",
		[TranslationKeys.ImportAiPhaseSkills] = "Skills",
		[TranslationKeys.ImportAiPhaseLanguages] = "Languages",
		[TranslationKeys.ImportAiPhaseCertificates] = "Certificates",
		[TranslationKeys.ImportAiPhaseProjects] = "Projects",
		[TranslationKeys.ImportAiPhaseLinks] = "Links",
		[TranslationKeys.ImportAiPhaseAdditional] = "Additional information",
		[TranslationKeys.QualityHintFlyoutTitle] = "Suggestions — {0}",
		[TranslationKeys.QualityHintGoToField] = "Go to field",
		[TranslationKeys.QualityHintDismiss] = "Dismiss",
		[TranslationKeys.QualityHintBadgeCount] = "{0}",
		[TranslationKeys.QualityHintBadgeAccessibility] = "{0} suggestions",
		[TranslationKeys.QualityHintSnackbarAfterImport] = "Import complete. Review suggestions on section badges.",
		[TranslationKeys.QualityHintSnackbarFirstSession] = "This CV has suggestions to improve — click the badges beside sections.",
		[TranslationKeys.QualityHintExportSummary] = "{0} suggestions — see section badges.",
		[TranslationKeys.QualityHintExportReview] = "Review",
		[TranslationKeys.QualityHintPersonalSummaryTooShort] = "Short summary — consider adding 2–3 sentences about your role and strengths.",
		[TranslationKeys.QualityHintPersonalSummaryTooLong] = "Summary is very long — recruiters often skim; consider shortening.",
		[TranslationKeys.QualityHintPersonalSummaryMissing] = "Summary is empty — add a brief overview of your experience and strengths.",
		[TranslationKeys.QualityHintPersonalMissingTitle] = "Professional title is empty — add a headline under your name.",
		[TranslationKeys.QualityHintWorkSectionEmpty] = "No work experience yet — add at least your most recent role.",
		[TranslationKeys.QualityHintWorkMissingDescription] = "A work entry has no description — add responsibilities or achievements.",
		[TranslationKeys.QualityHintWorkGenericDescription] = "Description looks generic — add measurable outcomes (numbers, scope, impact).",
		[TranslationKeys.QualityHintEducationSectionEmpty] = "No education entries — add your highest qualification if relevant.",
		[TranslationKeys.QualityHintSkillsSingleLargeGroup] = "Many skills in one group — split into categories (e.g. Frontend, Backend).",
		[TranslationKeys.QualityHintSkillsSectionEmpty] = "No skills listed — add core technologies or tools you use.",
		[TranslationKeys.QualityHintLanguagesSectionEmpty] = "No languages listed — add languages you can use professionally.",
		[TranslationKeys.QualityHintLinksDuplicatePersonalUrl] = "A link duplicates a URL already in personal information — consider removing it.",
		[TranslationKeys.QualityHintCertificatesSectionEmpty] = "No certificates listed — add relevant certifications if you have them.",
		[TranslationKeys.QualityHintProjectsSectionEmpty] = "No projects listed — add notable projects if relevant.",
		[TranslationKeys.QualityHintProjectsMissingDescription] = "A project has no description or highlights — add what you built or achieved.",
		[TranslationKeys.QualityHintImportReviewSection] = "This section has fields that may need review after import.",
		[TranslationKeys.QualityHintImportReviewField] = "This field was uncertain during import — double-check the content.",
		[TranslationKeys.AiSetupTitle] = "AI setup",
		[TranslationKeys.AiSetupDetecting] = "Detecting your system…",
		[TranslationKeys.AiSetupDetectionFailed] = "Could not read system information.",
		[TranslationKeys.AiSetupRetry] = "Retry",
		[TranslationKeys.AiSetupSystemSummary] = "{0} · {1} · {2} RAM",
		[TranslationKeys.AiSetupSystemPlatform] = "Operating system: {0}",
		[TranslationKeys.AiSetupSystemArchitecture] = "Architecture: {0}",
		[TranslationKeys.AiSetupSystemCpu] = "CPU cores: {0}",
		[TranslationKeys.AiSetupSystemRam] = "Memory: {0}",
		[TranslationKeys.AiSetupSystemDisk] = "Free disk space: {0}",
		[TranslationKeys.AiSetupSystemOllamaRunning] = "Ollama: running ({0} models installed)",
		[TranslationKeys.AiSetupSystemOllamaStopped] = "Ollama: not running",
		[TranslationKeys.AiSetupSystemDetailsTitle] = "Your system",
		[TranslationKeys.AiSetupRecommended] = "Recommended for your device",
		[TranslationKeys.AiSetupRequiresMoreMemory] = "Requires more memory than detected",
		[TranslationKeys.AiSetupOversizedWarning] = "Larger than recommended for your device — may run slowly or fail",
		[TranslationKeys.AiSetupReasonRecommended] = "Best fit for your device",
		[TranslationKeys.AiSetupDownload] = "Download model",
		[TranslationKeys.AiSetupDownloadConfirm] = "Download {0} (~{1})? This may use significant disk space.",
		[TranslationKeys.AiSetupDownloadConfirmOversized] = "Download {0} (~{1})? This model is larger than recommended for your device and may run slowly or fail.",
		[TranslationKeys.AiSetupOllamaNotRunning] = "Ollama is not running at {0}. ReVitae tried to start it — open the Ollama app manually, then try again.",
		[TranslationKeys.AiSetupOllamaNotInstalled] = "ReVitae will install the local AI engine automatically when you download a model.",
		[TranslationKeys.AiSetupOllamaInstallFailed] = "Could not set up the local AI engine automatically. Try Resume again, or install Ollama from https://ollama.com/download.",
		[TranslationKeys.AiSetupPullProgress] = "Downloading… {0}",
		[TranslationKeys.AiSetupPullComplete] = "Model downloaded and ready.",
		[TranslationKeys.AiSetupPullFailed] = "Download failed.",
		[TranslationKeys.AiSetupAlreadyDownloaded] = "Already on this computer",
		[TranslationKeys.AiSetupUnknownRam] = "Could not read total memory; recommendation may be conservative.",
		[TranslationKeys.AiSetupPrivacyNote] = "System detection runs only on this device. ReVitae does not send your hardware profile or CV data to ReVitae servers.",
		[TranslationKeys.AiSetupInsufficientDiskSpace] = "Not enough free disk space. About {0} is required; {1} available.",
		[TranslationKeys.AiSetupDiskSpaceUnknown] = "unknown",
		[TranslationKeys.AiSetupAllModels] = "All models",
		[TranslationKeys.AiSetupModelMeta] = "Download ~{0} · Min. RAM {1}",
		[TranslationKeys.AiSetupModelRemove] = "Remove model",
		[TranslationKeys.AiSetupModelRemoveConfirm] = "Remove {0} from this Mac? ReVitae will delete the model files from Ollama and clear its saved AI settings for this model.",
		[TranslationKeys.AiSetupModelCleanStale] = "Clean up failed download",
		[TranslationKeys.AiSetupModelCleanStaleConfirm] = "Clean up failed download for {0}? ReVitae will delete partial files from Ollama and reset download progress.",
		[TranslationKeys.AiSetupModelRemoveFailed] = "Could not remove the model. Make sure Ollama is running and try again.",
		[TranslationKeys.AiSetupModelRemoveBlockedActiveDownload] = "Wait until the current download finishes or stop it before removing a model.",
		[TranslationKeys.AiSetupModelRemoveComplete] = "Model removed.",
		[TranslationKeys.AiSetupModelCleanStaleComplete] = "Failed download cleaned up.",
		[TranslationKeys.AiSetupModelStaleDownload] = "Incomplete download — can be cleaned up",
		[TranslationKeys.AiSetupModelStatusDownloaded] = "Downloaded",
		[TranslationKeys.AiSetupModelStatusNotDownloaded] = "Not downloaded",
		[TranslationKeys.AiSetupModelStatusDownloading] = "Downloading…",
		[TranslationKeys.AiDownloadDockTooltip] = "AI model download — click for details",
		[TranslationKeys.AiDownloadBannerTitle] = "Downloading {0}",
		[TranslationKeys.AiDownloadBannerPaused] = "Download paused — {0}",
		[TranslationKeys.AiDownloadPercent] = "{0}%",
		[TranslationKeys.AiDownloadPercentUnknown] = "…",
		[TranslationKeys.AiDownloadPause] = "Pause",
		[TranslationKeys.AiDownloadResume] = "Resume",
		[TranslationKeys.AiDownloadStop] = "Stop download",
		[TranslationKeys.AiDownloadStopConfirm] = "Stop downloading {0}? Progress will be lost in ReVitae; Ollama may keep partial files.",
		[TranslationKeys.AiDownloadResumeOnStartup] = "Resuming model download…",
		[TranslationKeys.AiDownloadOllamaRequired] = "Start Ollama to continue the download.",
		[TranslationKeys.AiDownloadPreparingEngine] = "Preparing local AI engine…",
		[TranslationKeys.AiDownloadDownloadingEngine] = "Downloading local AI engine…",
		[TranslationKeys.AiDownloadStartingEngine] = "Starting local AI engine…",
		[TranslationKeys.AiDownloadPullingModel] = "Downloading model…",
		[TranslationKeys.AiDownloadRestartingAfterRecovery] = "Restarting download from scratch…",
		[TranslationKeys.AiDownloadFailed] = "Download failed.",
		[TranslationKeys.AiDownloadCompleted] = "Download complete.",
		[TranslationKeys.AiDownloadRefreshSystem] = "Refresh system info",
		[TranslationKeys.AiDownloadInsufficientDiskSpace] = "Not enough free disk space to continue. Free space and try again.",
		[TranslationKeys.AiDownloadHeaderInProgress] = "AI model download in progress",
		[TranslationKeys.AiModelGemma2_2bName] = "Gemma 2 2B",
		[TranslationKeys.AiModelPhi3MiniName] = "Phi-3 Mini",
		[TranslationKeys.AiModelLlama32_3bName] = "Llama 3.2 3B Instruct",
		[TranslationKeys.AiModelQwen25_3bName] = "Qwen 2.5 3B Instruct",
		[TranslationKeys.AiModelMistral7bName] = "Mistral 7B Instruct",
		[TranslationKeys.AiModelLlama31_8bName] = "Llama 3.1 8B Instruct",
		[TranslationKeys.AiModelGemma2_9bName] = "Gemma 2 9B",
		[TranslationKeys.AiModelQwen25_7bName] = "Qwen 2.5 7B Instruct",
		[TranslationKeys.AiModelMixtral8x7bName] = "Mixtral 8x7B Instruct",
		[TranslationKeys.AiModelLlama31_70bName] = "Llama 3.1 70B Instruct",
		[TranslationKeys.AiModelLlama33_70bName] = "Llama 3.3 70B",
		[TranslationKeys.AiSetupLocalModelsSection] = "Local models",
		[TranslationKeys.AiSetupOnlineProvidersSection] = "Online providers",
		[TranslationKeys.AiSetupProviderConfigure] = "Configure",
		[TranslationKeys.AiSetupProviderActivate] = "Activate",
		[TranslationKeys.AiSetupProviderDeactivate] = "Deactivate",
		[TranslationKeys.AiSetupProviderEdit] = "Edit",
		[TranslationKeys.AiSetupProviderNotConfigured] = "Not configured",
		[TranslationKeys.AiSetupProviderConfigured] = "Configured",
		[TranslationKeys.AiSetupProviderActive] = "Active",
		[TranslationKeys.AiSetupProviderSave] = "Save",
		[TranslationKeys.AiSetupProviderTest] = "Test",
		[TranslationKeys.AiSetupProviderTestSuccess] = "Connection successful.",
		[TranslationKeys.AiSetupProviderTestFailed] = "Connection failed: {0}",
		[TranslationKeys.AiSetupProviderSwitchConfirm] = "Switch active AI from {0} to {1}? When an online provider is active, text you send to AI features may be processed on that provider's servers.",
		[TranslationKeys.AiSetupOnlinePrivacyNote] = "When an online provider is active, text you send to AI features may be processed on that provider's servers.",
		[TranslationKeys.AiSetupActiveAiNone] = "No AI selected — configure a provider or activate a local model.",
		[TranslationKeys.AiSetupActiveAiLocal] = "Active: {0} (local)",
		[TranslationKeys.AiSetupActiveAiOnline] = "Active: {0} · {1}",
		[TranslationKeys.AiSetupActiveAiChange] = "Change",
		[TranslationKeys.AiSetupActiveAiEdit] = "Edit",
		[TranslationKeys.AiSetupProviderFreeTier] = "Free tier available",
		[TranslationKeys.AiSetupProviderLastTestOk] = "Last test: successful",
		[TranslationKeys.AiSetupProviderLastTestFailed] = "Last test: failed",
		[TranslationKeys.AiSetupProviderActivateUntested] = "Connection has not been tested successfully. Activate anyway?",
		[TranslationKeys.AiSetupProviderActivateAnyway] = "Activate anyway",
		[TranslationKeys.AiSetupProviderReset] = "Reset configuration",
		[TranslationKeys.AiSetupProviderResetConfirm] = "Remove saved configuration for {0}?",
		[TranslationKeys.AiSetupProviderRateLimited] = "Rate limited — try again later.",
		[TranslationKeys.AiSetupProviderInvalidKey] = "Invalid API key or insufficient permissions.",
		[TranslationKeys.AiSetupProviderModelNotFound] = "Model or deployment not found.",
		[TranslationKeys.AiSetupProviderUnavailable] = "Provider unavailable — try again later.",
		[TranslationKeys.AiSetupCustomBaseUrlHint] = "Examples: LM Studio at http://127.0.0.1:1234/v1, Ollama at http://127.0.0.1:11434/v1",
		[TranslationKeys.AiSetupProviderAdvanced] = "Advanced settings",
		[TranslationKeys.AiSetupProviderSaved] = "Configuration saved.",
		[TranslationKeys.AiSetupModelActivate] = "Activate",
		[TranslationKeys.AiSetupModelDeactivate] = "Deactivate",
		[TranslationKeys.AiSetupModelActive] = "Active",
		[TranslationKeys.AiSetupProviderFieldApiKey] = "API key",
		[TranslationKeys.AiSetupProviderFieldBaseUrl] = "Base URL",
		[TranslationKeys.AiSetupProviderFieldModelId] = "Model",
		[TranslationKeys.AiSetupProviderFieldDeploymentName] = "Deployment name",
		[TranslationKeys.AiSetupProviderFieldApiVersion] = "API version",
		[TranslationKeys.AiSetupProviderFieldOrganizationId] = "Organization ID (optional)",
		[TranslationKeys.AiSetupProviderFieldCustomModel] = "Custom model ID",
		[TranslationKeys.AiSetupProviderUseCaseQuickEdits] = "Good for: quick edits",
		[TranslationKeys.AiSetupProviderUseCaseImportAssist] = "Good for: import assist (039+)",
		[TranslationKeys.AiProviderOpenAiName] = "OpenAI",
		[TranslationKeys.AiProviderOpenAiDescription] = "GPT models via the official OpenAI API.",
		[TranslationKeys.AiProviderAnthropicName] = "Anthropic",
		[TranslationKeys.AiProviderAnthropicDescription] = "Claude models via the Anthropic Messages API.",
		[TranslationKeys.AiProviderGeminiName] = "Google Gemini",
		[TranslationKeys.AiProviderGeminiDescription] = "Gemini models via Google AI Studio.",
		[TranslationKeys.AiProviderGroqName] = "Groq",
		[TranslationKeys.AiProviderGroqDescription] = "Fast hosted inference for open models.",
		[TranslationKeys.AiProviderAzureName] = "Azure OpenAI",
		[TranslationKeys.AiProviderAzureDescription] = "Enterprise OpenAI deployments in Azure.",
		[TranslationKeys.AiProviderMistralName] = "Mistral AI",
		[TranslationKeys.AiProviderMistralDescription] = "Mistral models via the official API.",
		[TranslationKeys.AiProviderDeepSeekName] = "DeepSeek",
		[TranslationKeys.AiProviderDeepSeekDescription] = "DeepSeek chat models.",
		[TranslationKeys.AiProviderOpenRouterName] = "OpenRouter",
		[TranslationKeys.AiProviderOpenRouterDescription] = "Access many models through one API key.",
		[TranslationKeys.AiProviderCustomName] = "Custom (OpenAI-compatible)",
		[TranslationKeys.AiProviderCustomDescription] = "LM Studio, LocalAI, Ollama /v1, vLLM, or other compatible endpoints.",
		[TranslationKeys.AiSetupHeaderActiveOnline] = "Active AI: {0}",
		[TranslationKeys.AiSetupHeaderActiveLocal] = "Active AI: {0} (local)",
		[TranslationKeys.AiCvImproveWithAi] = "Improve with AI",
		[TranslationKeys.AiCvSetUpAi] = "Set up AI",
		[TranslationKeys.AiCvSuggestionTitle] = "AI suggestion",
		[TranslationKeys.AiCvSuggestionAccept] = "Accept",
		[TranslationKeys.AiCvSuggestionEdit] = "Edit in form",
		[TranslationKeys.AiCvSuggestionCancel] = "Cancel",
		[TranslationKeys.AiCvSuggestionRetry] = "Retry",
		[TranslationKeys.AiCvSuggestionLoading] = "Generating suggestion…",
		[TranslationKeys.AiCvBackendLocal] = "Local · {0}",
		[TranslationKeys.AiCvBackendOnline] = "Online · {0}",
		[TranslationKeys.AiCvOnlineSendConfirm] = "Text from this field will be sent to {0} for processing. Continue?",
		[TranslationKeys.AiCvNoBackendConfigured] = "No AI selected — open AI setup and activate a model or provider.",
		[TranslationKeys.AiCvOllamaUnavailable] = "Local Ollama is not reachable — check AI setup.",
		[TranslationKeys.AiCvEmptyResponse] = "The model returned an empty response. Try again.",
		[TranslationKeys.AiCvResponseTooLong] = "The suggestion was too long — try again or edit manually.",
		[TranslationKeys.AiCvTaskFailed] = "AI suggestion failed: {0}",
		[TranslationKeys.AiCvAskForTips] = "Ask AI for tips",
		[TranslationKeys.AiCvAdvisorTitle] = "AI tips · {0}",
		[TranslationKeys.AiCvAdvisorApply] = "Apply",
		[TranslationKeys.AiCvAdvisorClose] = "Close",
		[TranslationKeys.AiCvAdvisorEmpty] = "No suggestions for this section right now.",
		[TranslationKeys.AiCvTargetRoleLabel] = "Target role (optional)",
		[TranslationKeys.AiCvTargetJobDescLabel] = "Paste a job description to tailor suggestions (optional)",
		[TranslationKeys.AiCvMeasurableResults] = "Suggest measurable results",
		[TranslationKeys.AiCvEntityGuardWarning] = "AI may have added details not in your CV: {0}",
		[TranslationKeys.AiCvAdvisorRationalePrefix] = "Why:",
		[TranslationKeys.AiCvApplyUndo] = "Undo",
		[TranslationKeys.AiCvAdvisorCached] = "Showing cached tips",
		[TranslationKeys.AiCvAdvisorRefresh] = "Refresh",
		[TranslationKeys.AiImportEnhancePartial] = "Enhance with AI — fill the gaps in this import.",
		[TranslationKeys.AiImportFixFields] = "Fix uncertain fields with AI",
		[TranslationKeys.AiImportRepairReviewTitle] = "Review AI field fixes",
		[TranslationKeys.AiImportRepairField] = "{0}: {1} → {2}",
		[TranslationKeys.AiImportRepairMore] = "{0} more uncertain fields not included.",
	};

	private static readonly IReadOnlyDictionary<string, string> SlovakImportOverlay =
		new Dictionary<string, string>
		{
			[TranslationKeys.IntroHelper] =
				"Podporuje PDF, Word, OpenDocument, RTF, text, Markdown, HTML, JSON, XML, JPEG/PNG obrázky a ďalšie bežné formáty CV. "
				+ "Skenované alebo iba obrazové PDF a fotografie sa dajú importovať cez vstavané OCR, ak je k dispozícii.",
			[TranslationKeys.ImportRunningOcr] = "Rozpoznávanie textu z obrázka…",
			[TranslationKeys.ImportWarningOcrUsed] =
				"Súbor bol načítaný pomocou OCR. Skontrolujte prosím všetky polia.",
			[TranslationKeys.ImportErrorOcrUnavailable] = "OCR nie je na tomto systéme k dispozícii.",
			[TranslationKeys.ImportErrorOcrFailed] = "Text v tomto obrázku alebo skene sa nepodarilo rozpoznať.",
			[TranslationKeys.ImportPdfFileType] = "Podporované súbory CV",
			[TranslationKeys.ImportPdfOnlyFileType] = "PDF dokumenty",
			[TranslationKeys.ImportPlainTextFileType] = "Obyčajný text",
			[TranslationKeys.ImportRasterImageFileType] = "Obrázky (JPEG, PNG, …)",
			[TranslationKeys.ImportForceOcr] = "Importovať ako sken (OCR)",
		};

	private static readonly IReadOnlyDictionary<string, string> SlovakAiSetupOverlay =
		new Dictionary<string, string>
		{
			[TranslationKeys.OpenAiSetup] = "Otvoriť nastavenia AI",
			[TranslationKeys.AiSetupTitle] = "Nastavenia AI",
			[TranslationKeys.AiSetupDetecting] = "Detekcia vášho systému…",
			[TranslationKeys.AiSetupDetectionFailed] = "Nepodarilo sa načítať informácie o systéme.",
			[TranslationKeys.AiSetupRetry] = "Skúsiť znova",
			[TranslationKeys.AiSetupSystemSummary] = "{0} · {1} · {2} RAM",
			[TranslationKeys.AiSetupSystemPlatform] = "Operačný systém: {0}",
			[TranslationKeys.AiSetupSystemArchitecture] = "Architektúra: {0}",
			[TranslationKeys.AiSetupSystemCpu] = "Jadrá CPU: {0}",
			[TranslationKeys.AiSetupSystemRam] = "Pamäť: {0}",
			[TranslationKeys.AiSetupSystemDisk] = "Voľné miesto na disku: {0}",
			[TranslationKeys.AiSetupSystemOllamaRunning] = "Ollama: beží ({0} nainštalovaných modelov)",
			[TranslationKeys.AiSetupSystemOllamaStopped] = "Ollama: nebeží",
			[TranslationKeys.AiSetupSystemDetailsTitle] = "Váš systém",
			[TranslationKeys.AiSetupRecommended] = "Odporúčané pre vaše zariadenie",
			[TranslationKeys.AiSetupRequiresMoreMemory] = "Vyžaduje viac pamäte, než bolo zistené",
			[TranslationKeys.AiSetupOversizedWarning] = "Väčší než odporúčané pre vaše zariadenie — môže bežať pomaly alebo zlyhať",
			[TranslationKeys.AiSetupReasonRecommended] = "Najvhodnejšie pre vaše zariadenie",
			[TranslationKeys.AiSetupDownload] = "Stiahnuť model",
			[TranslationKeys.AiSetupDownloadConfirm] = "Stiahnuť {0} (~{1})? Môže to zabrať významné miesto na disku.",
			[TranslationKeys.AiSetupDownloadConfirmOversized] = "Stiahnuť {0} (~{1})? Tento model je väčší než odporúčané pre vaše zariadenie a môže bežať pomaly alebo zlyhať.",
			[TranslationKeys.AiSetupOllamaNotRunning] = "Ollama nebeží na {0}. ReVitae sa ju pokúsilo spustiť — otvorte aplikáciu Ollama ručne a skúste to znova.",
			[TranslationKeys.AiSetupOllamaNotInstalled] = "ReVitae nainštaluje lokálny AI engine automaticky pri sťahovaní modelu.",
			[TranslationKeys.AiSetupOllamaInstallFailed] = "Nepodarilo sa automaticky pripraviť lokálny AI engine. Skúste Pokračovať znova alebo nainštalujte Ollama z https://ollama.com/download.",
			[TranslationKeys.AiSetupPullProgress] = "Sťahovanie… {0}",
			[TranslationKeys.AiSetupPullComplete] = "Model bol stiahnutý a je pripravený.",
			[TranslationKeys.AiSetupPullFailed] = "Sťahovanie zlyhalo.",
			[TranslationKeys.AiSetupAlreadyDownloaded] = "Už je na tomto počítači",
			[TranslationKeys.AiSetupUnknownRam] = "Nepodarilo sa načítať celkovú pamäť; odporúčanie môže byť konzervatívne.",
			[TranslationKeys.AiSetupPrivacyNote] = "Detekcia systému prebieha len na tomto zariadení. ReVitae neodosiela profil hardvéru ani údaje CV na servery ReVitae.",
			[TranslationKeys.AiSetupInsufficientDiskSpace] = "Nedostatok voľného miesta na disku. Potrebných je približne {0}; k dispozícii {1}.",
			[TranslationKeys.AiSetupDiskSpaceUnknown] = "neznáme",
			[TranslationKeys.AiSetupAllModels] = "Všetky modely",
			[TranslationKeys.AiSetupModelMeta] = "Sťahovanie ~{0} · Min. RAM {1}",
			[TranslationKeys.AiSetupModelRemove] = "Odstrániť model",
			[TranslationKeys.AiSetupModelRemoveConfirm] = "Odstrániť {0} z tohto Macu? ReVitae zmaže súbory modelu v Ollama a vymaže uložené AI nastavenia pre tento model.",
			[TranslationKeys.AiSetupModelCleanStale] = "Vyčistiť neúspešné sťahovanie",
			[TranslationKeys.AiSetupModelCleanStaleConfirm] = "Vyčistiť neúspešné sťahovanie pre {0}? ReVitae zmaže čiastočné súbory v Ollama a resetuje priebeh sťahovania.",
			[TranslationKeys.AiSetupModelRemoveFailed] = "Model sa nepodarilo odstrániť. Skontrolujte, či beží Ollama, a skúste znova.",
			[TranslationKeys.AiSetupModelRemoveBlockedActiveDownload] = "Počkajte, kým sa dokončí aktuálne sťahovanie, alebo ho zastavte pred odstránením modelu.",
			[TranslationKeys.AiSetupModelRemoveComplete] = "Model bol odstránený.",
			[TranslationKeys.AiSetupModelCleanStaleComplete] = "Neúspešné sťahovanie bolo vyčistené.",
			[TranslationKeys.AiSetupModelStaleDownload] = "Nedokončené sťahovanie — dá sa vyčistiť",
			[TranslationKeys.AiSetupModelStatusDownloaded] = "Stiahnuté",
			[TranslationKeys.AiSetupModelStatusNotDownloaded] = "Nestiahnuté",
			[TranslationKeys.AiSetupModelStatusDownloading] = "Sťahuje sa…",
			[TranslationKeys.AiDownloadDockTooltip] = "Sťahovanie AI modelu — kliknite pre podrobnosti",
			[TranslationKeys.AiDownloadBannerTitle] = "Sťahovanie {0}",
			[TranslationKeys.AiDownloadBannerPaused] = "Sťahovanie pozastavené — {0}",
			[TranslationKeys.AiDownloadPercent] = "{0} %",
			[TranslationKeys.AiDownloadPercentUnknown] = "…",
			[TranslationKeys.AiDownloadPause] = "Pozastaviť",
			[TranslationKeys.AiDownloadResume] = "Pokračovať",
			[TranslationKeys.AiDownloadStop] = "Zastaviť sťahovanie",
			[TranslationKeys.AiDownloadStopConfirm] = "Zastaviť sťahovanie {0}? Priebeh sa stratí v ReVitae; Ollama môže ponechať čiastočné súbory.",
			[TranslationKeys.AiDownloadResumeOnStartup] = "Obnovuje sa sťahovanie modelu…",
			[TranslationKeys.AiDownloadOllamaRequired] = "Spustite Ollama pre pokračovanie sťahovania.",
			[TranslationKeys.AiDownloadPreparingEngine] = "Príprava lokálneho AI enginu…",
			[TranslationKeys.AiDownloadDownloadingEngine] = "Sťahovanie lokálneho AI enginu…",
			[TranslationKeys.AiDownloadStartingEngine] = "Spúšťanie lokálneho AI enginu…",
			[TranslationKeys.AiDownloadPullingModel] = "Sťahovanie modelu…",
			[TranslationKeys.AiDownloadRestartingAfterRecovery] = "Sťahovanie sa reštartuje od začiatku…",
			[TranslationKeys.AiDownloadFailed] = "Sťahovanie zlyhalo.",
			[TranslationKeys.AiDownloadCompleted] = "Sťahovanie dokončené.",
			[TranslationKeys.AiDownloadRefreshSystem] = "Obnoviť informácie o systéme",
			[TranslationKeys.AiDownloadInsufficientDiskSpace] = "Nedostatok voľného miesta na disku. Uvoľnite miesto a skúste znova.",
			[TranslationKeys.AiDownloadHeaderInProgress] = "Prebieha sťahovanie AI modelu",
			[TranslationKeys.AiModelGemma2_2bName] = "Gemma 2 2B",
			[TranslationKeys.AiModelPhi3MiniName] = "Phi-3 Mini",
			[TranslationKeys.AiModelLlama32_3bName] = "Llama 3.2 3B Instruct",
			[TranslationKeys.AiModelQwen25_3bName] = "Qwen 2.5 3B Instruct",
			[TranslationKeys.AiModelMistral7bName] = "Mistral 7B Instruct",
			[TranslationKeys.AiModelLlama31_8bName] = "Llama 3.1 8B Instruct",
			[TranslationKeys.AiModelGemma2_9bName] = "Gemma 2 9B",
			[TranslationKeys.AiModelQwen25_7bName] = "Qwen 2.5 7B Instruct",
			[TranslationKeys.AiModelMixtral8x7bName] = "Mixtral 8x7B Instruct",
			[TranslationKeys.AiModelLlama31_70bName] = "Llama 3.1 70B Instruct",
			[TranslationKeys.AiModelLlama33_70bName] = "Llama 3.3 70B",
			[TranslationKeys.AiSetupLocalModelsSection] = "Lokálne modely",
			[TranslationKeys.AiSetupOnlineProvidersSection] = "Online poskytovatelia",
			[TranslationKeys.AiSetupProviderConfigure] = "Nastaviť",
			[TranslationKeys.AiSetupProviderActivate] = "Aktivovať",
			[TranslationKeys.AiSetupProviderDeactivate] = "Deaktivovať",
			[TranslationKeys.AiSetupProviderEdit] = "Upraviť",
			[TranslationKeys.AiSetupProviderNotConfigured] = "Nenastavené",
			[TranslationKeys.AiSetupProviderConfigured] = "Nastavené",
			[TranslationKeys.AiSetupProviderActive] = "Aktívne",
			[TranslationKeys.AiSetupProviderSave] = "Uložiť",
			[TranslationKeys.AiSetupProviderTest] = "Otestovať",
			[TranslationKeys.AiSetupProviderTestSuccess] = "Pripojenie úspešné.",
			[TranslationKeys.AiSetupProviderTestFailed] = "Pripojenie zlyhalo: {0}",
			[TranslationKeys.AiSetupProviderSwitchConfirm] = "Prepnúť aktívne AI z {0} na {1}? Pri aktívnom online poskytovateľovi môžu byť texty odoslané do AI spracované na serveroch poskytovateľa.",
			[TranslationKeys.AiSetupOnlinePrivacyNote] = "Pri aktívnom online poskytovateľovi môžu byť texty odoslané do AI funkcií spracované na serveroch poskytovateľa.",
			[TranslationKeys.AiSetupActiveAiNone] = "Nie je vybraté AI — nastavte poskytovateľa alebo aktivujte lokálny model.",
			[TranslationKeys.AiSetupActiveAiLocal] = "Aktívne: {0} (lokálne)",
			[TranslationKeys.AiSetupActiveAiOnline] = "Aktívne: {0} · {1}",
			[TranslationKeys.AiSetupActiveAiChange] = "Zmeniť",
			[TranslationKeys.AiSetupActiveAiEdit] = "Upraviť",
			[TranslationKeys.AiSetupProviderFreeTier] = "Dostupná bezplatná úroveň",
			[TranslationKeys.AiSetupProviderLastTestOk] = "Posledný test: úspešný",
			[TranslationKeys.AiSetupProviderLastTestFailed] = "Posledný test: zlyhal",
			[TranslationKeys.AiSetupProviderActivateUntested] = "Pripojenie nebolo úspešne otestované. Aktivovať aj tak?",
			[TranslationKeys.AiSetupProviderActivateAnyway] = "Aktivovať aj tak",
			[TranslationKeys.AiSetupProviderReset] = "Resetovať konfiguráciu",
			[TranslationKeys.AiSetupProviderResetConfirm] = "Odstrániť uloženú konfiguráciu pre {0}?",
			[TranslationKeys.AiSetupProviderRateLimited] = "Limit požiadaviek — skúste neskôr.",
			[TranslationKeys.AiSetupProviderInvalidKey] = "Neplatný API kľúč alebo nedostatočné oprávnenia.",
			[TranslationKeys.AiSetupProviderModelNotFound] = "Model alebo deployment sa nenašiel.",
			[TranslationKeys.AiSetupProviderUnavailable] = "Poskytovateľ nedostupný — skúste neskôr.",
			[TranslationKeys.AiSetupCustomBaseUrlHint] = "Príklady: LM Studio http://127.0.0.1:1234/v1, Ollama http://127.0.0.1:11434/v1",
			[TranslationKeys.AiSetupProviderAdvanced] = "Pokročilé nastavenia",
			[TranslationKeys.AiSetupProviderSaved] = "Konfigurácia uložená.",
			[TranslationKeys.AiSetupModelActivate] = "Aktivovať",
			[TranslationKeys.AiSetupModelDeactivate] = "Deaktivovať",
			[TranslationKeys.AiSetupModelActive] = "Aktívne",
			[TranslationKeys.AiSetupProviderFieldApiKey] = "API kľúč",
			[TranslationKeys.AiSetupProviderFieldBaseUrl] = "Base URL",
			[TranslationKeys.AiSetupProviderFieldModelId] = "Model",
			[TranslationKeys.AiSetupProviderFieldDeploymentName] = "Názov deploymentu",
			[TranslationKeys.AiSetupProviderFieldApiVersion] = "Verzia API",
			[TranslationKeys.AiSetupProviderFieldOrganizationId] = "Organization ID (voliteľné)",
			[TranslationKeys.AiSetupProviderFieldCustomModel] = "Vlastné ID modelu",
			[TranslationKeys.AiSetupProviderUseCaseQuickEdits] = "Vhodné na: rýchle úpravy",
			[TranslationKeys.AiSetupProviderUseCaseImportAssist] = "Vhodné na: import assist (039+)",
			[TranslationKeys.AiProviderOpenAiName] = "OpenAI",
			[TranslationKeys.AiProviderOpenAiDescription] = "GPT modely cez oficiálne OpenAI API.",
			[TranslationKeys.AiProviderAnthropicName] = "Anthropic",
			[TranslationKeys.AiProviderAnthropicDescription] = "Claude modely cez Anthropic Messages API.",
			[TranslationKeys.AiProviderGeminiName] = "Google Gemini",
			[TranslationKeys.AiProviderGeminiDescription] = "Gemini modely cez Google AI Studio.",
			[TranslationKeys.AiProviderGroqName] = "Groq",
			[TranslationKeys.AiProviderGroqDescription] = "Rýchla hostovaná inferencia pre open modely.",
			[TranslationKeys.AiProviderAzureName] = "Azure OpenAI",
			[TranslationKeys.AiProviderAzureDescription] = "Enterprise OpenAI deploymenty v Azure.",
			[TranslationKeys.AiProviderMistralName] = "Mistral AI",
			[TranslationKeys.AiProviderMistralDescription] = "Mistral modely cez oficiálne API.",
			[TranslationKeys.AiProviderDeepSeekName] = "DeepSeek",
			[TranslationKeys.AiProviderDeepSeekDescription] = "DeepSeek chat modely.",
			[TranslationKeys.AiProviderOpenRouterName] = "OpenRouter",
			[TranslationKeys.AiProviderOpenRouterDescription] = "Prístup k mnohým modelom cez jeden API kľúč.",
			[TranslationKeys.AiProviderCustomName] = "Vlastné (OpenAI-compatible)",
			[TranslationKeys.AiProviderCustomDescription] = "LM Studio, LocalAI, Ollama /v1, vLLM alebo iné kompatibilné endpointy.",
			[TranslationKeys.AiSetupHeaderActiveOnline] = "Aktívne AI: {0}",
			[TranslationKeys.AiSetupHeaderActiveLocal] = "Aktívne AI: {0} (lokálne)",
			[TranslationKeys.AiCvImproveWithAi] = "Vylepšiť pomocou AI",
			[TranslationKeys.AiCvSetUpAi] = "Nastaviť AI",
			[TranslationKeys.AiCvSuggestionTitle] = "Návrh od AI",
			[TranslationKeys.AiCvSuggestionAccept] = "Prijať",
			[TranslationKeys.AiCvSuggestionEdit] = "Upraviť vo formulári",
			[TranslationKeys.AiCvSuggestionCancel] = "Zrušiť",
			[TranslationKeys.AiCvSuggestionRetry] = "Skúsiť znova",
			[TranslationKeys.AiCvSuggestionLoading] = "Generujem návrh…",
			[TranslationKeys.AiCvBackendLocal] = "Lokálne · {0}",
			[TranslationKeys.AiCvBackendOnline] = "Online · {0}",
			[TranslationKeys.AiCvOnlineSendConfirm] = "Text z tohto poľa bude odoslaný poskytovateľovi {0} na spracovanie. Pokračovať?",
			[TranslationKeys.AiCvNoBackendConfigured] = "Nie je vybrané AI — otvorte nastavenia AI a aktivujte model alebo poskytovateľa.",
			[TranslationKeys.AiCvOllamaUnavailable] = "Lokálna Ollama nie je dostupná — skontrolujte nastavenia AI.",
			[TranslationKeys.AiCvEmptyResponse] = "Model vrátil prázdnu odpoveď. Skúste to znova.",
			[TranslationKeys.AiCvResponseTooLong] = "Návrh bol príliš dlhý — skúste znova alebo upravte ručne.",
			[TranslationKeys.AiCvTaskFailed] = "Návrh od AI zlyhal: {0}",
			[TranslationKeys.AiCvAskForTips] = "Spýtať sa AI na tipy",
			[TranslationKeys.AiCvAdvisorTitle] = "Tipy od AI · {0}",
			[TranslationKeys.AiCvAdvisorApply] = "Použiť",
			[TranslationKeys.AiCvAdvisorClose] = "Zavrieť",
			[TranslationKeys.AiCvAdvisorEmpty] = "Pre túto sekciu momentálne nie sú návrhy.",
			[TranslationKeys.AiCvTargetRoleLabel] = "Cieľová pozícia (voliteľné)",
			[TranslationKeys.AiCvTargetJobDescLabel] = "Vložte popis pozície pre prispôsobenie návrhov (voliteľné)",
			[TranslationKeys.AiCvMeasurableResults] = "Navrhnúť merateľné výsledky",
			[TranslationKeys.AiCvEntityGuardWarning] = "AI mohla pridať údaje, ktoré nie sú vo vašom CV: {0}",
			[TranslationKeys.AiCvAdvisorRationalePrefix] = "Prečo:",
			[TranslationKeys.AiCvApplyUndo] = "Späť",
			[TranslationKeys.AiCvAdvisorCached] = "Zobrazujú sa uložené tipy",
			[TranslationKeys.AiCvAdvisorRefresh] = "Obnoviť",
			[TranslationKeys.AiImportEnhancePartial] = "Vylepšiť pomocou AI — doplňte medzery v tomto importe.",
			[TranslationKeys.AiImportFixFields] = "Opraviť neisté polia pomocou AI",
			[TranslationKeys.AiImportRepairReviewTitle] = "Skontrolovať opravy polí od AI",
			[TranslationKeys.AiImportRepairField] = "{0}: {1} → {2}",
			[TranslationKeys.AiImportRepairMore] = "Ďalšie {0} neisté polia neboli zahrnuté.",
			[TranslationKeys.ExportCategoryImages] = "Obrázky",
			[TranslationKeys.ExportFormatImages] = "Obrázky strán",
			[TranslationKeys.ExportFormatImagesHint] = "PNG, JPEG alebo WebP — jeden súbor na stranu",
			[TranslationKeys.ExportImageOptionsTitle] = "Možnosti exportu obrázkov",
			[TranslationKeys.ExportImageFormatLabel] = "Formát obrázka",
			[TranslationKeys.ExportImageFormatPng] = "PNG (bezztrátové)",
			[TranslationKeys.ExportImageFormatJpeg] = "JPEG (menší súbor)",
			[TranslationKeys.ExportImageFormatWebp] = "WebP (moderný web)",
			[TranslationKeys.ExportImageDeliveryLabel] = "Spôsob doručenia",
			[TranslationKeys.ExportImageDeliveryZip] = "Jeden ZIP archív",
			[TranslationKeys.ExportImageDeliveryZipHint] = "Všetky strany v jednom .zip súbore",
			[TranslationKeys.ExportImageDeliverySeparate] = "Samostatné súbory",
			[TranslationKeys.ExportImageDeliverySeparateHint] = "Uložiť každú stranu do priečinka",
			[TranslationKeys.ExportImageQualityLabel] = "Kvalita",
			[TranslationKeys.ExportImageScaleLabel] = "Rozlíšenie",
			[TranslationKeys.ExportImageScale1x] = "Štandardné (1×)",
			[TranslationKeys.ExportImageScale2x] = "Vysoké (2×)",
			[TranslationKeys.ExportImagePagesLabel] = "Strany",
			[TranslationKeys.ExportImagePagesAll] = "Všetky strany",
			[TranslationKeys.ExportImagePagesRange] = "Rozsah strán",
			[TranslationKeys.ExportImagePageFromLabel] = "Od",
			[TranslationKeys.ExportImagePageToLabel] = "Do",
			[TranslationKeys.ExportImageRangeInvalid] = "Zadajte platný rozsah strán (Od ≤ Do, v rámci celkového počtu).",
			[TranslationKeys.ExportImageSizeEstimate] = "{0} strán · ~{1} ({2})",
			[TranslationKeys.ExportImageSizeEstimateUnknown] = "Počítam veľkosť…",
			[TranslationKeys.ExportImageProgressRendering] = "Vykresľujem stranu {0} z {1}…",
			[TranslationKeys.ExportImageProgressWriting] = "Zapisujem súbory…",
			[TranslationKeys.ExportImageExportButton] = "Exportovať obrázky",
			[TranslationKeys.ExportImageBackButton] = "Späť na formáty",
			[TranslationKeys.ExportImageOptionsRequired] = "Chýbajú možnosti exportu obrázkov.",
			[TranslationKeys.ExportImageTooManyPages] = "Toto CV má príliš veľa strán na export ako obrázky (max {0}).",
			[TranslationKeys.ExportImageRasterFailed] = "Nepodarilo sa vykresliť strany CV ako obrázky.",
			[TranslationKeys.ExportZipFileType] = "ZIP archív",
			[TranslationKeys.ExportFolderPickerTitle] = "Vyberte priečinok pre obrázky CV",
			[TranslationKeys.ExportedImagesToZip] = "Exportovaných {0} strán do {1}.",
			[TranslationKeys.ExportedImagesToFolder] = "Exportovaných {0} strán do priečinka.",
			[TranslationKeys.ProjectSave] = "Uložiť",
			[TranslationKeys.ProjectSaveAs] = "Uložiť ako",
			[TranslationKeys.ProjectOpen] = "Otvoriť",
			[TranslationKeys.ProjectSaveDialogTitle] = "Uložiť projekt CV",
			[TranslationKeys.ProjectOpenDialogTitle] = "Otvoriť CV",
			[TranslationKeys.ProjectSaved] = "Uložené {0}",
			[TranslationKeys.ProjectOpened] = "Otvorené {0}",
			[TranslationKeys.ProjectSaveFailed] = "Projekt sa nepodarilo uložiť.",
			[TranslationKeys.ProjectOpenFailed] = "Projekt sa nepodarilo otvoriť.",
			[TranslationKeys.ProjectOpenEmpty] = "Súbor projektu neobsahuje žiadne údaje CV.",
			[TranslationKeys.ProjectUntitled] = "CV bez názvu",
			[TranslationKeys.ProjectUnsavedIndicator] = "Neuložené zmeny",
			[TranslationKeys.ProjectUnsavedConfirmTitle] = "Uložiť zmeny?",
			[TranslationKeys.ProjectUnsavedConfirmMessage] = "CV má neuložené zmeny. Uložiť pred pokračovaním?",
			[TranslationKeys.ProjectUnsavedSave] = "Uložiť",
			[TranslationKeys.ProjectUnsavedDiscard] = "Neukladať",
			[TranslationKeys.ProjectRecentTitle] = "Nedávne projekty",
			[TranslationKeys.ProjectRecentClear] = "Vymazať zoznam",
			[TranslationKeys.ProjectRecentClearConfirmTitle] = "Vymazať nedávne projekty?",
			[TranslationKeys.ProjectRecentClearConfirmMessage] = "Odstráni sa zoznam nedávnych projektov. Uložené súbory na disku sa nezmažú.",
			[TranslationKeys.ProjectRecentMissing] = "Súbor už neexistuje",
			[TranslationKeys.ProjectRecoveryTitle] = "Obnoviť neuloženú prácu?",
			[TranslationKeys.ProjectRecoveryMessage] = "ReVitae našlo automaticky uložené CV po neočakávanom ukončení.",
			[TranslationKeys.ProjectRecoveryRestore] = "Obnoviť",
			[TranslationKeys.ProjectRecoveryDiscard] = "Zahodiť",
			[TranslationKeys.ProjectSettingsPartiallyIgnored] = "Niektoré nastavenia editora boli ignorované (novší formát).",
			[TranslationKeys.ProjectSavedWithValidationErrors] = "Projekt uložený — pred exportom opravte chyby validácie.",
			[TranslationKeys.ProjectFileType] = "Projekt ReVitae",
			[TranslationKeys.ProjectGenericJsonFileType] = "JSON súbor",
			[TranslationKeys.IntroOpenProject] = "Otvoriť uložený projekt",
			[TranslationKeys.ImportAiTryButton] = "Skúsiť AI import",
			[TranslationKeys.IntroImportTryAi] = "Skúsiť AI import",
			[TranslationKeys.ReplaceImportTryAi] = "Skúsiť AI import",
			[TranslationKeys.ImportAiEnhanceButton] = "Vylepšiť pomocou AI",
			[TranslationKeys.ImportAiProgressTitle] = "AI import",
			[TranslationKeys.ImportAiProgressStep] = "Krok {0} z {1} — {2}",
			[TranslationKeys.ImportAiProgressBatch] = "(dávka {0} z {1})",
			[TranslationKeys.ImportAiReviewTitle] = "Skontrolovať AI import",
			[TranslationKeys.ImportAiReviewSummaryTitle] = "Súhrn sekcií",
			[TranslationKeys.ImportAiReviewSummaryBefore] = "Pred",
			[TranslationKeys.ImportAiReviewSummaryAfter] = "Po (AI)",
			[TranslationKeys.ImportAiReviewSectionsImproved] = "Vylepšené sekcie: {0}",
			[TranslationKeys.ImportAiReviewPersonalPartial] = "čiastočné",
			[TranslationKeys.ImportAiReviewPersonalComplete] = "úplné",
			[TranslationKeys.ImportAiReviewEmptyDash] = "—",
			[TranslationKeys.ImportAiReviewEntryCount] = "{0} záznamov",
			[TranslationKeys.ImportAiPhotoNotExtracted] = "AI import vyplní len textové polia. Profilovú fotku pridajte ručne.",
			[TranslationKeys.ImportAiReviewDetails] = "Detaily",
			[TranslationKeys.ImportAiReviewWarning] = "Obsah vytvorený AI — pred exportom skontrolujte všetky polia.",
			[TranslationKeys.ImportAiReviewApply] = "Použiť vo formulári",
			[TranslationKeys.ImportAiReviewCancel] = "Zrušiť",
			[TranslationKeys.ImportAiReviewMergeEmpty] = "Vyplniť len prázdne polia",
			[TranslationKeys.ImportAiOnlineConfirm] = "Text CV bude odoslaný do {0} vo viacerých krokoch. Pokračovať?",
			[TranslationKeys.ImportAiFailed] = "AI import nevedel extrahovať použiteľné údaje CV.",
			[TranslationKeys.ImportAiPartialWarning] = "Niektoré kroky zlyhali — dôkladne skontrolujte neúplné sekcie.",
			[TranslationKeys.ImportAiNoBackend] = "Nastavte AI pre použitie AI importu.",
			[TranslationKeys.ImportAiBannerIncomplete] = "Import môže byť neúplný.",
			[TranslationKeys.ImportWarningAiAssisted] = "Tento návrh bol vytvorený s pomocou AI — overte všetky polia.",
			[TranslationKeys.ImportWarningAiPartial] = "AI import preskočil niektoré sekcie kvôli chybám.",
			[TranslationKeys.ImportAiPhasePersonal] = "Osobné údaje",
			[TranslationKeys.ImportAiPhaseWork] = "Pracovné skúsenosti",
			[TranslationKeys.ImportAiPhaseEducation] = "Vzdelanie",
			[TranslationKeys.ImportAiPhaseSkills] = "Zručnosti",
			[TranslationKeys.ImportAiPhaseLanguages] = "Jazyky",
			[TranslationKeys.ImportAiPhaseCertificates] = "Certifikáty",
			[TranslationKeys.ImportAiPhaseProjects] = "Projekty",
			[TranslationKeys.ImportAiPhaseLinks] = "Odkazy",
			[TranslationKeys.ImportAiPhaseAdditional] = "Doplňujúce informácie",
			[TranslationKeys.SetupShowAiWizardAgain] = "Znova zobraziť sprievodcu nastavením AI",
			[TranslationKeys.FirstLaunchAiWizardTitle] = "Nastavenie AI (voliteľné)",
			[TranslationKeys.FirstLaunchAiWizardWelcomeLead] = "ReVitae môže použiť AI na import skenovaných CV a návrhy úprav textu.",
			[TranslationKeys.FirstLaunchAiWizardWelcomeReview] = "Pred použitím vždy skontrolujete návrhy.",
			[TranslationKeys.FirstLaunchAiWizardWelcomePrivacy] = "Lokálne modely bežia vo vašom zariadení. Online poskytovatelia spracúvajú text na svojich serveroch.",
			[TranslationKeys.FirstLaunchAiWizardWelcomeLanguage] = "Jazyk",
			[TranslationKeys.FirstLaunchAiWizardWelcomeChangeLanguage] = "Zmeniť",
			[TranslationKeys.FirstLaunchAiWizardChoosePathTitle] = "Ako chcete používať AI?",
			[TranslationKeys.FirstLaunchAiWizardPathLocalTitle] = "Bezplatný lokálny model",
			[TranslationKeys.FirstLaunchAiWizardPathLocalSubtitle] = "Stiahne sa raz; potom funguje offline. Odporúčané pri dostatku RAM a miesta na disku.",
			[TranslationKeys.FirstLaunchAiWizardPathOnlineTitle] = "Online poskytovateľ",
			[TranslationKeys.FirstLaunchAiWizardPathOnlineSubtitle] = "Použite API kľúč (OpenAI, Anthropic a ďalší).",
			[TranslationKeys.FirstLaunchAiWizardPathSkipTitle] = "Preskočiť",
			[TranslationKeys.FirstLaunchAiWizardPathSkipSubtitle] = "Nastavte AI neskôr — funkcie ostanú v paneli nástrojov.",
			[TranslationKeys.FirstLaunchAiWizardPathOfflineTitle] = "Nebudem používať AI",
			[TranslationKeys.FirstLaunchAiWizardPathOfflineSubtitle] = "Tvorte a exportujte CV bez AI návrhov a importu.",
			[TranslationKeys.FirstLaunchAiWizardLocalDetecting] = "Analyzujem váš systém…",
			[TranslationKeys.FirstLaunchAiWizardLocalDetectionFailed] = "Nepodarilo sa analyzovať systém. Skúste znova alebo preskočte.",
			[TranslationKeys.FirstLaunchAiWizardLocalRecommended] = "Odporúčané pre váš systém",
			[TranslationKeys.FirstLaunchAiWizardLocalDownloadActivate] = "Stiahnuť a aktivovať",
			[TranslationKeys.FirstLaunchAiWizardLocalDownloadInProgress] = "Prebieha sťahovanie — môžete pokračovať.",
			[TranslationKeys.FirstLaunchAiWizardOnlineMoreProviders] = "Viac poskytovateľov…",
			[TranslationKeys.FirstLaunchAiWizardCompleteActiveLocal] = "AI je pripravené — {0} (lokálne).",
			[TranslationKeys.FirstLaunchAiWizardCompleteActiveOnline] = "AI je pripravené — {0}.",
			[TranslationKeys.FirstLaunchAiWizardCompleteSkipped] = "AI nie je nastavené. Kedykoľvek ho nastavíte cez ikonu robota.",
			[TranslationKeys.FirstLaunchAiWizardCompleteRemindLater] = "AI zatiaľ nie je nastavené. Nastavte ho cez ikonu robota alebo Nastavenia.",
			[TranslationKeys.FirstLaunchAiWizardCompleteOfflineOnly] = "AI funkcie sú skryté. Zapnite ich v Nastaveniach alebo cez ikonu robota.",
			[TranslationKeys.FirstLaunchAiWizardCompleteChangeAiHint] = "AI nastavenia zmeníte kedykoľvek cez ikonu robota alebo Nastavenia.",
			[TranslationKeys.FirstLaunchAiWizardSkipConfirm] = "Preskočiť nastavenie AI?",
			[TranslationKeys.FirstLaunchAiWizardOfflineConfirm] = "Skryť AI funkcie v ReVitae? Neskôr ich zapnete v Nastaveniach.",
			[TranslationKeys.FirstLaunchAiWizardSkip] = "Preskočiť",
			[TranslationKeys.FirstLaunchAiWizardBack] = "Späť",
			[TranslationKeys.FirstLaunchAiWizardNext] = "Ďalej",
			[TranslationKeys.FirstLaunchAiWizardGetStarted] = "Začať",
			[TranslationKeys.FirstLaunchAiWizardStepIndicator] = "Krok {0} z {1}",
			[TranslationKeys.FirstLaunchAiWizardRetry] = "Skúsiť znova",
		};

	private static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> TranslationOverlays =
		new Dictionary<string, IReadOnlyDictionary<string, string>>
		{
			["sk"] = MergeOverlays(
				MergeOverlays(
					Overlay("Vytvorte jednoduchý náhľad CV a exportujte plain PDF.", "Nastavenia", "Šablóny", "Jazyk", "Zavrieť", "Meno", "Priezvisko", "Profesijný titul", "Telefón", "Lokalita", "Krátke zhrnutie", "Náhľad", "Vybrané", "Pracovné skúsenosti", "Pridajte najprv poslednú pozíciu. Poradie môžete zmeniť neskôr.", "Rozbaliť náhľad", "Rozšírený náhľad"),
					SlovakImportOverlay),
				SlovakAiSetupOverlay),
			["cs"] = Overlay("Vytvořte jednoduchý náhled CV a exportujte plain PDF.", "Nastavení", "Šablony", "Jazyk", "Zavřít", "Jméno", "Příjmení", "Profesní titul", "Telefon", "Lokalita", "Krátké shrnutí", "Náhled", "Vybráno", "Pracovní zkušenosti", "Nejprve přidejte poslední roli. Pořadí můžete změnit později.", "Rozbalit náhled", "Rozšířený náhled"),
			["es"] = Overlay("Crea una vista previa simple del CV y exporta un PDF básico.", "Configuración", "Plantillas", "Idioma", "Cerrar", "Nombre", "Apellido", "Título profesional", "Teléfono", "Ubicación", "Resumen breve", "Vista previa", "Seleccionado", "Experiencia laboral", "Agrega tu rol más reciente primero. Puedes reordenar después.", "Expandir vista previa", "Vista previa ampliada"),
			["fr"] = Overlay("Créez un aperçu simple du CV et exportez un PDF léger.", "Configuration", "Modèles", "Langue", "Fermer", "Prénom", "Nom", "Titre professionnel", "Téléphone", "Lieu", "Résumé court", "Aperçu", "Sélectionné", "Expérience professionnelle", "Ajoutez d'abord votre poste le plus récent. Vous pourrez réorganiser ensuite.", "Agrandir l'aperçu", "Aperçu agrandi"),
			["de"] = Overlay("Erstellen Sie eine einfache CV-Vorschau und exportieren Sie ein schlichtes PDF.", "Einrichtung", "Vorlagen", "Sprache", "Schließen", "Vorname", "Nachname", "Berufsbezeichnung", "Telefon", "Standort", "Kurzprofil", "Vorschau", "Ausgewählt", "Berufserfahrung", "Fügen Sie zuerst Ihre aktuelle Rolle hinzu. Die Reihenfolge können Sie später ändern.", "Vorschau vergrößern", "Erweiterte Vorschau"),
			["pt"] = Overlay("Crie uma pré-visualização simples do CV e exporte um PDF básico.", "Configuração", "Modelos", "Idioma", "Fechar", "Nome", "Sobrenome", "Título profissional", "Telefone", "Localização", "Resumo curto", "Pré-visualização", "Selecionado", "Experiência profissional", "Adicione primeiro a função mais recente. Você pode reordenar depois.", "Expandir pré-visualização", "Pré-visualização ampliada"),
			["it"] = Overlay("Crea un'anteprima semplice del CV ed esporta un PDF leggero.", "Configurazione", "Modelli", "Lingua", "Chiudi", "Nome", "Cognome", "Titolo professionale", "Telefono", "Località", "Breve riepilogo", "Anteprima", "Selezionato", "Esperienza lavorativa", "Aggiungi prima il ruolo più recente. Potrai riordinare in seguito.", "Espandi anteprima", "Anteprima ingrandita"),
			["nl"] = Overlay("Maak een eenvoudige cv-preview en exporteer een eenvoudige PDF.", "Instellingen", "Sjablonen", "Taal", "Sluiten", "Voornaam", "Achternaam", "Functietitel", "Telefoon", "Locatie", "Korte samenvatting", "Voorbeeld", "Geselecteerd", "Werkervaring", "Voeg eerst je meest recente rol toe. Je kunt later herschikken.", "Voorbeeld vergroten", "Uitgevouwen voorbeeld"),
			["pl"] = Overlay("Utwórz prosty podgląd CV i wyeksportuj lekki PDF.", "Ustawienia", "Szablony", "Język", "Zamknij", "Imię", "Nazwisko", "Tytuł zawodowy", "Telefon", "Lokalizacja", "Krótkie podsumowanie", "Podgląd", "Wybrano", "Doświadczenie zawodowe", "Najpierw dodaj ostatnie stanowisko. Kolejność możesz zmienić później.", "Powiększ podgląd", "Powiększony podgląd"),
			["uk"] = Overlay("Створіть простий попередній перегляд CV та експортуйте простий PDF.", "Налаштування", "Шаблони", "Мова", "Закрити", "Ім'я", "Прізвище", "Професійний заголовок", "Телефон", "Місцезнаходження", "Короткий опис", "Перегляд", "Вибрано", "Досвід роботи", "Спочатку додайте останню роль. Порядок можна змінити пізніше.", "Розгорнути перегляд", "Розширений перегляд"),
			["zh-Hans"] = Overlay("创建简单的简历预览并导出基础 PDF。", "设置", "模板", "语言", "关闭", "名", "姓", "职业标题", "电话", "位置", "简短摘要", "预览", "已选择", "工作经历", "请先添加最近的工作。之后可以重新排序。", "展开预览", "展开的预览")
		};

	private readonly IReadOnlyDictionary<string, string> _translations;

	public AppLocalizer(string languageCode)
	{
		LanguageCode = DetectSupportedLanguage(languageCode);
		_translations = BuildTranslations(LanguageCode);
	}

	public string LanguageCode { get; }

	public static AppLocalizer FromSystemCulture()
	{
		return new AppLocalizer(CultureInfo.CurrentUICulture.Name);
	}

	public static string DetectSupportedLanguage(CultureInfo culture)
	{
		return DetectSupportedLanguage(culture.Name);
	}

	public static string DetectSupportedLanguage(string cultureName)
	{
		if (string.IsNullOrWhiteSpace(cultureName))
		{
			return FallbackLanguageCode;
		}

		var normalized = cultureName.Equals("zh", StringComparison.OrdinalIgnoreCase)
			? "zh-Hans"
			: cultureName;

		if (SupportedLanguages.Any(language => language.Code.Equals(normalized, StringComparison.OrdinalIgnoreCase)))
		{
			return SupportedLanguages.First(language => language.Code.Equals(normalized, StringComparison.OrdinalIgnoreCase)).Code;
		}

		var parent = normalized.Split('-', StringSplitOptions.RemoveEmptyEntries)[0];
		if (parent.Equals("zh", StringComparison.OrdinalIgnoreCase))
		{
			return "zh-Hans";
		}

		var parentMatch = SupportedLanguages.FirstOrDefault(language => language.Code.Equals(parent, StringComparison.OrdinalIgnoreCase));
		return parentMatch?.Code ?? FallbackLanguageCode;
	}

	public string Get(string key)
	{
		return _translations.TryGetValue(key, out var value) ? value : key;
	}

	public string Format(string key, params object[] values)
	{
		return string.Format(CultureInfo.CurrentCulture, Get(key), values);
	}

	public static IReadOnlyDictionary<string, string> GetTranslations(string languageCode)
	{
		return BuildTranslations(DetectSupportedLanguage(languageCode));
	}

	private static IReadOnlyDictionary<string, string> BuildTranslations(string languageCode)
	{
		var translations = new Dictionary<string, string>(EnglishTranslations, StringComparer.Ordinal);
		foreach (var theme in CvThemedTemplateRegistry.All)
		{
			translations[theme.NameKey] = theme.NameEnglish;
			translations[theme.DescriptionKey] = theme.DescriptionEnglish;
		}

		if (TranslationOverlays.TryGetValue(languageCode, out var overlay))
		{
			foreach (var (key, value) in overlay)
			{
				translations[key] = value;
			}
		}

		return translations;
	}

	private static IReadOnlyDictionary<string, string> MergeOverlays(
		IReadOnlyDictionary<string, string> baseOverlay,
		IReadOnlyDictionary<string, string> extraOverlay)
	{
		var merged = new Dictionary<string, string>(baseOverlay);
		foreach (var (key, value) in extraOverlay)
		{
			merged[key] = value;
		}

		return merged;
	}

	private static IReadOnlyDictionary<string, string> Overlay(
		string subtitle,
		string setup,
		string templates,
		string language,
		string close,
		string firstName,
		string lastName,
		string professionalTitle,
		string phone,
		string location,
		string shortSummary,
		string preview,
		string selected,
		string workExperience,
		string workExperienceEmptyHint,
		string openExpandPreview,
		string previewExpandTitle)
	{
		return new Dictionary<string, string>
		{
			[TranslationKeys.HeaderSubtitle] = subtitle,
			[TranslationKeys.OpenSetup] = setup,
			[TranslationKeys.OpenTemplates] = templates,
			[TranslationKeys.OpenExpandPreview] = openExpandPreview,
			[TranslationKeys.Setup] = setup,
			[TranslationKeys.Templates] = templates,
			[TranslationKeys.Language] = language,
			[TranslationKeys.Close] = close,
			[TranslationKeys.FirstName] = firstName,
			[TranslationKeys.LastName] = lastName,
			[TranslationKeys.ProfessionalTitle] = professionalTitle,
			[TranslationKeys.Phone] = phone,
			[TranslationKeys.Location] = location,
			[TranslationKeys.ShortSummary] = shortSummary,
			[TranslationKeys.Preview] = preview,
			[TranslationKeys.PreviewExpandTitle] = previewExpandTitle,
			[TranslationKeys.Selected] = selected,
			[TranslationKeys.WorkExperience] = workExperience,
			[TranslationKeys.WorkExperienceEmptyHint] = workExperienceEmptyHint
		};
	}
}
